"use client"

import React, { createContext, useContext, useEffect } from "react"

type Language = "en" | "fr" | "ar"
type Direction = "ltr" | "rtl"

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
    dir: Direction
    toggleLanguage: () => void
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
    fr: {
        "common.currency": "MAD",
        // Navigation
        "nav.shop": "Boutique",
        "nav.collections": "Collections",
        "nav.about": "À propos",
        "nav.faq": "FAQ",
        "nav.search": "Rechercher",
        "nav.shop_now": "Acheter",
        "nav.view_all_collections": "Voir toutes les collections",

        // Header Popups
        "header.categories": "Catégories",
        "header.browse_by_category": "Parcourir par catégorie",
        "header.face_care": "Ordinateurs & Portables",
        "header.face_care_desc": "Stations de travail haute performance",
        "header.hair_care": "Serveurs & Stockage",
        "header.hair_care_desc": "Solutions pour entreprises",
        "header.body_care": "Imprimantes & Scanners",
        "header.body_care_desc": "Impression professionnelle",
        "header.gift_sets": "Composants",
        "header.gift_sets_desc": "Processeurs, RAM & plus",
        "header.new_arrival": "Nouveautés",
        "header.argan_elixir": "Gaming",
        "header.argan_elixir_desc": "Performance ultime pour gamers",
        "header.signature": "Entreprise",
        "header.essentials": "Bureau",
        "header.premium": "Gaming",

        // Hero
        "hero.title_prefix": "Didali",
        "hero.title_suffix": "Store",
        "hero.subtitle": "Leader de la distribution informatique au Maroc. Grossiste en PC, serveurs, imprimantes et plus.",
        "hero.shop_collection": "Parcourir les produits",
        "hero.explore_best_sellers": "Voir les meilleures ventes",
        "hero.fast_delivery": "Livraison Rapide",
        "hero.secure_checkout": "Paiement Sécurisé",
        "hero.easy_returns": "Garantie Officielle",
        "hero.pure_argan_oil": "Produits Authentiques",
        "hero.cold_pressed": "Meilleurs Prix",

        // Sections
        "section.featured_collections": "Départements Vedettes",
        "section.featured_desc": "Découvrez notre large gamme d'équipements informatiques",
        "section.best_sellers": "Catégories",
        "section.best_sellers_desc": "Afficher toutes nos catégories ici",
        "section.all_categories": "Tout",
        "section.view_all_products": "Voir tous les produits",
        "section.load_more": "Charger plus",
        "section.why_choose": "Pourquoi choisir Didali Store ?",
        "section.organic": "100% Authentique",
        "section.organic_desc": "Produits authentiques des grandes marques",
        "section.award_winning": "Leader du marché",
        "section.award_winning_desc": "Plus de 20 ans d'expérience",
        "section.cruelty_free": "Garantie Complète",
        "section.cruelty_free_desc": "Garantie constructeur officielle",
        "section.handcrafted": "Support Expert",
        "section.handcrafted_desc": "Conseils techniques par des pros",
        "section.limited_offer": "Offre Limitée",
        "section.promo_title": "25% de remise sur votre 1ère commande",
        "section.promo_desc": "Profitez de la meilleure offre pour votre première commande. Utilisez le code WELCOME25.",
        "section.get_offer": "Profiter de l'offre",
        "section.hurry_up": "Dépêchez-vous !",
        "section.view_collection": "Voir la collection",

        // Newsletter
        "newsletter.title": "Restez informé",
        "newsletter.desc": "Abonnez-vous pour des offres exclusives et les nouveaux lancements de produits.",
        "newsletter.placeholder": "Entrez votre email",
        "newsletter.subscribe": "S'abonner",
        "newsletter.disclaimer": "En vous abonnant, vous acceptez notre politique de confidentialité. Désinscription à tout moment.",

        // WhatsApp
        "whatsapp.title": "Restez connecté sur WhatsApp",
        "whatsapp.desc": "Rejoignez notre liste VIP pour des remises exclusives et un accès prioritaire aux nouveautés.",
        "whatsapp.placeholder": "Numéro de téléphone",
        "whatsapp.button": "Rejoindre maintenant",
        "whatsapp.success_title": "Vous êtes sur la liste !",
        "whatsapp.success_desc": "Merci de votre inscription. Un cadeau de bienvenue vous a été envoyé.",
        "whatsapp.disclaimer": "En rejoignant, vous acceptez de recevoir des messages marketing sur WhatsApp.",
        "whatsapp.register_another": "Inscrire un autre numéro",
        "whatsapp.verified_updates": "Mises à jour vérifiées",
        "whatsapp.processing": "Traitement...",

        // Footer
        "footer.company": "Entreprise",
        "footer.support": "Support",
        "footer.legal": "Légal",
        "footer.our_story": "Notre histoire",
        "footer.sustainability": "Durabilité",
        "footer.press": "Presse",
        "footer.careers": "Carrières",
        "footer.contact_us": "Contactez-nous",
        "footer.shipping_info": "Livraison",
        "footer.track_order": "Suivre ma commande",
        "footer.privacy_policy": "Politique de confidentialité",
        "footer.terms": "Conditions d'utilisation",
        "footer.refund_policy": "Politique de remboursement",
        "footer.cookies": "Cookies",
        "footer.rights": "Tous droits réservés.",
        "footer.about_desc": "Didali Store - Votre partenaire de confiance pour le matériel et les solutions informatiques au Maroc.",
        "footer.privacy_short": "Confidentialité",
        "footer.terms_short": "Conditions",
        "footer.system_status": "Système Opérationnel",

        // Product & Cart
        "product.add_to_cart": "Ajouter au panier",
        "product.reviews": "avis",
        "product.in_stock": "En Stock",
        "product.low_stock": "Stock Faible",
        "product.out_of_stock": "Rupture de stock",
        "product.select_size": "Choisir la taille",
        "product.quantity": "Quantité",
        "product.features": "Caractéristiques Clés",
        "product.specifications": "Spécifications Techniques",
        "product.warranty": "Garantie & Support",
        "product.you_may_also_like": "Vous aimerez aussi",
        "cart.your_cart_empty": "Votre panier est vide",
        "cart.empty_desc": "Il semblerait que vous n'ayez rien ajouté à votre panier pour le moment.",
        "cart.start_shopping": "Commencer vos achats",
        "cart.shopping_cart": "Panier",
        "cart.items": "articles",
        "cart.order_summary": "Résumé de la commande",
        "cart.subtotal": "Sous-total",
        "cart.shipping": "Livraison",
        "cart.free": "Gratuit",
        "cart.total": "Total",
        "cart.proceed_checkout": "Passer à la caisse",
        "cart.promo_code": "Code Promo",
        "cart.apply": "Appliquer",
        "cart.applied": "Appliqué",
        "cart.enter_code": "Entrer le code",
        "cart.discount_applied": "Remise appliquée !",
        "cart.add_more_shipping": "Ajoutez plus pour la livraison gratuite",
        "cart.continue_shopping": "Continuer vos achats",
        "cart.trust.shipping": "Livraison Rapide",
        "cart.trust.secure": "Paiement Sécurisé",
        "cart.trust.returns": "Retours sous 30 jours",

        // Order statuses (for labels/badges)
        "order.status.pending": "En attente",
        "order.status.processing": "En traitement",
        "order.status.shipped": "Expédiée",
        "order.status.delivered": "Livrée",
        "order.status.cancelled": "Annulée",

        // Generic Statuses (used in Manager pages)
        "status.pending": "En attente",
        "status.processing": "En traitement",
        "status.shipped": "Expédiée",
        "status.delivered": "Livrée",
        "status.cancelled": "Annulée",

        // FAQ
        "faq.title": "Questions Fréquentes",
        "faq.subtitle": "Tout ce que vous devez savoir sur nos produits",
        "faq.q1": "Quels types de produits vendez-vous ?",
        "faq.a1": "Nous sommes un distributeur grossiste d'équipements informatiques, incluant PC, serveurs, imprimantes et réseaux.",
        "faq.q2": "Offrez-vous une garantie ?",
        "faq.a2": "Oui, tous nos produits sont couverts par la garantie officielle du fabricant.",
        "faq.q3": "Vendez-vous aux particuliers ?",
        "faq.a3": "Nous servons principalement les entreprises et revendeurs, mais vendons aussi aux particuliers.",
        "faq.q4": "Où êtes-vous situés ?",
        "faq.a4": "Nous sommes basés au Maroc et servons des clients dans tout le royaume.",
        "faq.q5": "Comment obtenir un devis ?",
        "faq.a5": "Vous pouvez demander un devis via notre site web ou contacter notre équipe commerciale.",
        "faq.q6": "Fournissez-vous un support technique ?",
        "faq.a6": "Oui, notre équipe d'experts peut vous assister pour vos questions techniques et la conception de solutions.",

        // Checkout
        "checkout.title": "Paiement",
        "checkout.contact_info": "Informations de contact",
        "checkout.full_name": "Nom complet",
        "checkout.phone": "Numéro de téléphone",
        "checkout.email": "Email (Optionnel)",
        "checkout.city": "Ville",
        "checkout.address": "Adresse",
        "checkout.pay": "Payer",
        "checkout.processing": "Traitement...",
        "checkout.success_title": "Commande Confirmée !",
        "checkout.continue_shopping": "Continuer vos achats",
        "checkout.cancel_title": "Paiement Annulé",
        "checkout.cancel_desc": "Votre paiement a été annulé. Aucun débit n'a été effectué.",
        "checkout.return_cart": "Retour au panier",
        "checkout.retry": "Réessayer",
        "validation.required": "Ce champ est requis",
        "validation.phone": "Veuillez entrer un numéro valide (min 10 car.)",
        "validation.email": "Veuillez entrer un email valide",

        // Success Page
        "success.thank_you": "Merci",
        "success.order_confirmed": "Votre commande est confirmée",
        "checkout.success_desc": "Nous avons bien reçu votre commande. Nous vous appellerons bientôt pour confirmer.",
        "success.coupon_title": "Un cadeau pour vous",
        "success.coupon_desc": "Utilisez ce code pour 20% de réduction sur votre prochain achat",
        "success.order_summary": "Résumé de la commande",

        // Timer
        "timer.days": "Jours",
        "timer.hours": "Heures",
        "timer.minutes": "Min",
        "timer.seconds": "Sec",
        "timer.loading": "Chargement...",

        // Accessibility
        "accessibility.go_to_slide": "Aller à la diapositive",

        // Dashboard - Admin
        "dashboard.admin.title": "Tableau de Bord",
        "dashboard.admin.overview": "Aperçu détaillé",
        "dashboard.admin.search_placeholder": "Rechercher des commandes, clients, produits... (Ctrl+K)",
        "dashboard.admin.export": "Exporter",
        "dashboard.admin.import": "Importer",

        "admin.dashboard.recent_orders.title": "Commandes récentes",
        "admin.dashboard.recent_orders.view_all": "Voir tout",
        "admin.dashboard.recent_orders.loading": "Chargement...",
        "admin.dashboard.recent_orders.empty": "Aucune commande récente.",
        "admin.dashboard.recent_orders.col_order_id": "N° Commande",
        "admin.dashboard.recent_orders.col_customer": "Client",
        "admin.dashboard.recent_orders.col_email": "Email",
        "admin.dashboard.recent_orders.col_amount": "Montant",
        "admin.dashboard.recent_orders.col_status": "Statut",
        "admin.dashboard.recent_orders.col_action": "Action",

        // Admin Orders
        "admin.orders.title": "Commandes",
        "admin.orders.subtitle": "Gérer et suivre les commandes",
        "admin.orders.export": "Exporter",
        "admin.orders.create_order": "Créer une commande",
        "admin.orders.search_placeholder": "Rechercher des commandes...",
        "admin.orders.status.all": "Tout",
        "admin.orders.status.processing": "En traitement",
        "admin.orders.status.delivered": "Livrée",
        "admin.orders.status.pending": "En attente",
        "admin.orders.status.cancelled": "Annulée",
        "admin.orders.table.order": "Commande",
        "admin.orders.table.date": "Date",
        "admin.orders.table.customer": "Client",
        "admin.orders.table.items": "Articles",
        "admin.orders.table.total": "Total",
        "admin.orders.table.status": "Statut",
        "admin.orders.table.actions": "Actions",
        "admin.orders.loading": "Chargement des commandes...",
        "admin.orders.no_orders": "Aucune commande trouvée",
        "admin.orders.no_orders_match": "Aucune commande ne correspond à vos critères",
        "admin.orders.showing": "Affichage de {current} sur {total} commandes",
        "admin.orders.view_details": "Voir les détails",

        // Admin Products
        "admin.products.title": "Produits",
        "admin.products.subtitle": "Gérez votre inventaire",
        "admin.products.import_csv": "Importer CSV",
        "admin.products.manage_categories": "Gérer les catégories",
        "admin.products.add_product": "Ajouter un produit",
        "admin.products.category_name_en": "Nom de catégorie (Anglais)",
        "admin.products.category_name_ar": "Nom de catégorie (Arabe)",
        "admin.products.add": "Ajouter",
        "admin.products.search_categories": "Rechercher des catégories...",
        "admin.products.delete_category_confirm": "Supprimer cette catégorie ? Les produits l'utilisant devront être recatégorisés.",
        "admin.products.stats.total_products": "Total Produits",
        "admin.products.stats.total_inventory": "Inventaire Total",
        "admin.products.stats.low_stock": "Stock Faible",
        "admin.products.stats.out_of_stock": "Rupture de Stock",
        "admin.products.search_placeholder": "Rechercher des produits...",
        "admin.products.table.product": "Produit",
        "admin.products.table.category": "Catégorie",
        "admin.products.table.price": "Prix",
        "admin.products.table.stock": "Stock",
        "admin.products.table.status": "Statut",
        "admin.products.table.actions": "Actions",
        "admin.products.no_products": "Aucun produit trouvé correspondant à vos critères.",
        "admin.products.delete_product_confirm": "Êtes-vous sûr de vouloir supprimer ce produit ?",
        "admin.products.qty": "Qté",
        "admin.products.units": "unités",
        "admin.products.uploading": "Téléchargement...",

        // Admin Sidebar
        "admin.sidebar.dashboard": "Tableau de bord",
        "admin.sidebar.orders": "Commandes",
        "admin.sidebar.products": "Produits",
        "admin.sidebar.customers": "Clients",
        "admin.sidebar.resellers": "Revendeurs",
        "admin.sidebar.account_managers": "Gestionnaires de compte",
        "admin.sidebar.delivery_men": "Logisticiens",
        "admin.sidebar.shipping": "Livraison",
        "admin.sidebar.analytics": "Analytique",
        "admin.sidebar.hero_carousel": "Promo",
        "admin.sidebar.whatsapp_leads": "Leads WhatsApp",
        "admin.sidebar.contact_messages": "Messages de contact",
        "admin.sidebar.career_applications": "Candidatures",
        "admin.sidebar.settings": "Paramètres",
        "admin.sidebar.logout": "Déconnexion",

        // Admin Hero
        "admin.hero.title": "Promo",
        "admin.hero.subtitle": "Personnalisez le curseur de votre page d'accueil. Les images de haute qualité (16:9 ou 4:3) fonctionnent le mieux. Liez les diapositives aux produits pour stimuler les ventes. Important : Assurez-vous d'activer les diapositives pour qu'elles apparaissent dans la boutique.",
        "admin.hero.add_slide": "Ajouter une Diapositive",
        "admin.hero.refresh": "Actualiser",
        "admin.hero.change_image": "Changer l'Image",
        "admin.hero.title_label": "Titre",
        "admin.hero.subtitle_label": "Sous-titre",
        "admin.hero.placeholder_title": "Titre de la Diapositive",
        "admin.hero.placeholder_subtitle": "Petit texte au-dessus du titre",
        "admin.hero.linked_product": "Produit Lié",
        "admin.hero.no_link": "Aucun Lien (Image uniquement)",
        "admin.hero.select_product": "Sélectionner un Produit",
        "admin.hero.active": "Actif",
        "admin.hero.inactive": "Inactif",
        "admin.hero.save": "Enregistrer",
        "admin.hero.saved": "Enregistré",
        "admin.hero.delete": "Supprimer",
        "admin.hero.max_size": "Images max 5 Mo",
        "admin.hero.recommended_size": "Recommandé : 1920x1080px ou 1200x1200px",
        "admin.hero.slides_configured": "{count} Diapositives configurées",
        "admin.hero.toast.upload_image": "Veuillez télécharger un fichier image",
        "admin.hero.toast.image_large": "La taille de l'image doit être inférieure à 5 Mo",
        "admin.hero.toast.uploading": "Téléchargement de l'image...",
        "admin.hero.toast.upload_success": "Image téléchargée avec succès",
        "admin.hero.toast.upload_fail": "Échec de la mise à jour de l'image",
        "admin.hero.toast.adding": "Ajout d'une nouvelle diapositive...",
        "admin.hero.toast.add_success": "Diapositive ajoutée ! Téléchargez une image maintenant.",
        "admin.hero.toast.add_fail": "Échec de l'ajout de la diapositive",
        "admin.hero.toast.delete_confirm": "Êtes-vous sûr de vouloir supprimer cette diapositive ?",
        "admin.hero.toast.deleting": "Suppression de la diapositive...",
        "admin.hero.toast.delete_success": "Diapositive supprimée",
        "admin.hero.toast.delete_fail": "Échec de la suppression de la diapositive",
        "admin.hero.toast.no_image_fail": "Impossible d'activer une diapositive sans image",
        "admin.hero.toast.activating": "Activation...",
        "admin.hero.toast.deactivating": "Désactivation...",
        "admin.hero.toast.status_success_on": "Diapositive activée",
        "admin.hero.toast.status_success_off": "Diapositive désactivée",
        "admin.hero.toast.status_fail": "Échec de la mise à jour du statut",
        "admin.hero.toast.save_success": "Enregistré avec succès",
        "admin.hero.toast.save_fail": "Échec de l'enregistrement",

        // Admin Contacts
        "admin.contacts.back": "Retour au tableau de bord",
        "admin.contacts.title": "Messages de contact",
        "admin.contacts.list_title": "Messages des clients, partenaires et distributeurs",
        "admin.contacts.subtitle": "Cliquez sur le bouton \"Afficher\" pour lire le contenu complet du message dans une boîte de dialogue.",
        "admin.contacts.table.name": "Nom",
        "admin.contacts.table.email": "E-mail",
        "admin.contacts.table.phone": "Téléphone",
        "admin.contacts.table.type": "Type",
        "admin.contacts.table.message": "Message",
        "admin.contacts.table.date": "Date",
        "admin.contacts.no_messages": "Aucun message pour le moment. Connectez le formulaire de contact à une base de données pour voir les messages ici.",
        "admin.contacts.view": "Afficher",
        "admin.contacts.details_title": "Détails du message",
        "admin.contacts.label.name": "Nom :",
        "admin.contacts.label.email": "E-mail :",
        "admin.contacts.label.phone": "Téléphone :",
        "admin.contacts.label.company": "Entreprise :",
        "admin.contacts.label.type": "Type :",

        // Admin Careers
        "admin.careers.back": "Retour au tableau de bord",
        "admin.careers.title": "Candidatures",
        "admin.careers.list_title": "Candidatures pour rejoindre l'équipe",
        "admin.careers.subtitle": "Cliquez sur le bouton \"Afficher\" sur chaque ligne pour lire le résumé complet de la candidature dans une boîte de dialogue.",
        "admin.careers.table.name": "Nom",
        "admin.careers.table.email": "E-mail",
        "admin.careers.table.phone": "Téléphone",
        "admin.careers.table.role": "Rôle",
        "admin.careers.table.cv": "Fichier CV",
        "admin.careers.table.summary": "Résumé",
        "admin.careers.table.date": "Date",
        "admin.careers.no_applications": "Aucune candidature pour le moment. Connectez le formulaire de carrière à une base de données pour voir les candidatures ici.",
        "admin.careers.open_cv": "Ouvrir le CV",
        "admin.careers.no_file": "Aucun fichier",
        "admin.careers.view": "Afficher",
        "admin.careers.details_title": "Détails de la candidature",
        "admin.careers.label.name": "Nom :",
        "admin.careers.label.email": "E-mail :",
        "admin.careers.label.phone": "Téléphone :",
        "admin.careers.label.role": "Rôle :",
        "admin.careers.label.cv": "Fichier CV :",

        // Admin Order details (extra labels)
        "admin.orders.update_status": "Mettre à jour le statut",
        "admin.orders.timeline_title": "Historique des statuts",
        "admin.orders.timeline_empty": "Aucun journal disponible.",
        "admin.orders.customer_title": "Client",
        "admin.orders.customer_company": "Entreprise",
        "admin.orders.customer_contact": "Contact",
        "admin.orders.customer_email": "E-mail",

        // Admin Settings
        "admin.settings.title": "Configuration de l'Administration",
        "admin.settings.subtitle": "Paramètres globaux pour Didali Store",
        "admin.settings.reset": "Réinitialiser",
        "admin.settings.update": "Mettre à jour les systèmes",
        "admin.settings.toast.success": "Paramètres mis à jour avec succès",
        "admin.settings.toast.error": "Échec de la mise à jour des paramètres",
        "admin.settings.toast.push_sent": "Envoyé à {count} appareil(s)",
        "admin.settings.toast.push_no_sub": "Aucun abonnement actif trouvé pour ce magasin.",
        "admin.settings.toast.push_fail": "Échec du déclenchement de la notification de test",
        "admin.settings.tabs.general": "Général",
        "admin.settings.tabs.marketing": "Marketing",
        "admin.settings.tabs.payments": "Paiements",
        "admin.settings.tabs.alerts": "Alertes",
        "admin.settings.tabs.security": "Sécurité",
        "admin.settings.tabs.team": "Équipe",
        "admin.settings.general.action_required": "Action Requise",
        "admin.settings.general.caught_up": "Tout est à jour ! Pas d'alertes urgentes.",
        "admin.settings.general.reminders_title": "Rappels Internes",
        "admin.settings.general.reminders_desc": "Utilisez les notes internes sur les profils des revendeurs pour suivre les évaluations de performance et les besoins de suivi. Celles-ci sont partagées avec les administrateurs mais cachées aux revendeurs.",
        "admin.settings.general.identity_title": "Identité et Localisation",
        "admin.settings.general.label.store_name": "Nom du magasin",
        "admin.settings.general.label.support_email": "E-mail d'assistance",
        "admin.settings.general.label.currency": "Devise principale",
        "admin.settings.general.channels_title": "Canaux de contact",
        "admin.settings.general.label.whatsapp": "Numéro WhatsApp Business",
        "admin.settings.general.label.phone": "Ligne d'assistance directe",
        "admin.settings.marketing.title": "Annonces et Promotions Globales",
        "admin.settings.marketing.label.en_content": "Contenu Anglais",
        "admin.settings.marketing.label.ar_content": "Contenu Arabe",
        "admin.settings.marketing.label.announcement": "Annonce d'en-tête",
        "admin.settings.marketing.label.hero_title": "Titre de la section Hero",
        "admin.settings.marketing.label.hero_subtitle": "Sous-titre Hero",
        "admin.settings.marketing.label.promo_code": "Code Promo Actif",
        "admin.settings.marketing.promo_desc": "Appliqué lors du paiement et affiché dans certaines sections du magasin.",
        "admin.settings.payments.gateways_title": "Passerelles Standards",
        "admin.settings.payments.cod_title": "Paiement à la livraison (COD)",
        "admin.settings.payments.cod_desc": "Paiement standard au Maroc",
        "admin.settings.payments.cheque_title": "Paiement par chèque",
        "admin.settings.payments.cheque_desc": "Pour les entreprises et les sociétés",
        "admin.settings.payments.label.payee_info": "Informations sur le bénéficiaire",
        "admin.settings.payments.wire_title": "Virements Bancaires",
        "admin.settings.payments.transfer_title": "Virement",
        "admin.settings.payments.transfer_desc": "Paiement basé sur IBAN / RIB",
        "admin.settings.payments.label.banking_details": "Coordonnées bancaires",
        "admin.settings.alerts.title": "Notifications Push",
        "admin.settings.alerts.desc": "Alertes système en temps réel pour les commandes et le statut des stocks directement sur votre mobile ou votre bureau.",
        "admin.settings.alerts.global_toggle": "Service Push Global",
        "admin.settings.alerts.global_desc": "Interrupteur principal pour le moteur de notifications du magasin.",
        "admin.settings.alerts.register_device": "Enregistrer l'appareil actuel",
        "admin.settings.alerts.send_ping": "Envoyer un ping système",
        "admin.settings.alerts.guide_title": "Guide de configuration",
        "admin.settings.alerts.guide_ios_title": "iOS / iPhone",
        "admin.settings.alerts.guide_ios_desc": "1. Ouvrez cette page dans Safari\n2. Appuyez sur Partager → \"Sur l'écran d'accueil\"\n3. Ouvrez depuis l'écran d'accueil et abonnez-vous.",
        "admin.settings.alerts.guide_android_title": "Android / Bureau",
        "admin.settings.alerts.guide_android_desc": "Le navigateur doit être ouvert ou les tâches en arrière-plan activées. Fonctionne nativement sur Chrome/Edge.",
        "admin.settings.security.title": "Protection du Tableau de Bord",
        "admin.settings.security.desc": "Le code PIN administrateur protège les opérations sensibles et l'entrée dans le tableau de bord.",
        "admin.settings.security.label.pin": "Code PIN d'accès au système",
        "admin.settings.security.warning": "Attention : La modification du code PIN prendra effet immédiatement sur tous les points d'entrée administratifs.",
        "admin.settings.team.title": "Tableau de Bord du Gestionnaire de Compte",
        "admin.settings.team.label.fallback": "Message de statut par défaut",
        "admin.settings.team.fallback_desc": "Affiché dans le widget 'Action Requise' lorsqu'il n'y a pas de commandes en attente.",
        "admin.settings.team.label.guidance": "Conseils Internes",
        "admin.settings.team.guidance_desc": "Affiché dans le widget 'Rappels Internes' sur le tableau de bord du gestionnaire.",

        // Admin WhatsApp
        "admin.whatsapp.back": "Retour au tableau de bord",
        "admin.whatsapp.title": "Leads WhatsApp",
        "admin.whatsapp.list_title": "Liste des abonnés WhatsApp",
        "admin.whatsapp.subtitle": "Cette page est un espace réservé pour afficher les numéros du formulaire.",
        "admin.whatsapp.table.country": "Code pays",
        "admin.whatsapp.table.phone": "Téléphone",
        "admin.whatsapp.table.date": "Abonné le",
        "admin.whatsapp.no_data": "Aucune donnée pour le moment.",

        // Admin Shipping
        "admin.shipping.title": "Règles de Livraison",
        "admin.shipping.subtitle": "Contrôlez les frais de livraison et les seuils de livraison gratuite pour différents types de clients.",
        "admin.shipping.refresh": "Actualiser",
        "admin.shipping.save_rules": "Enregistrer les Règles",
        "admin.shipping.customer_rules": "Règles Client {role}",
        "admin.shipping.reseller_rules": "Règles Revendeur",
        "admin.shipping.partner_rules": "Règles Partenaire",
        "admin.shipping.wholesaler_rules": "Règles Grossiste",
        "admin.shipping.configure_costs": "Configurer les coûts et seuils",
        "admin.shipping.status": "Statut",
        "admin.shipping.base_cost": "Frais de Livraison de Base",
        "admin.shipping.fixed_fee_desc": "Frais fixes ajoutés aux commandes inférieures au seuil.",
        "admin.shipping.free_threshold_amount": "Livraison Gratuite (Montant)",
        "admin.shipping.amount_required_desc": "Montant requis pour la livraison gratuite.",
        "admin.shipping.free_threshold_items": "Livraison Gratuite (Articles)",
        "admin.shipping.min_items_desc": "Nombre minimum d'articles requis pour la livraison gratuite.",
        "admin.shipping.order_logic": "Logique de commande :",
        "admin.shipping.rule_logic_desc": "Les commandes coûteront {price} {currency} sauf si elles dépassent {threshold} {currency} ou contiennent au moins {items} articles.",
        "admin.shipping.rule_disabled": "La règle de livraison est actuellement désactivée.",
        "admin.shipping.no_rules": "Aucune règle de livraison trouvée. Veuillez vérifier la configuration de la base de données.",
        "admin.shipping.retry": "Réessayer le chargement",
        "admin.shipping.success_update": "Paramètres de livraison mis à jour avec succès",
        "admin.shipping.error_update": "Échec de la mise à jour des paramètres",

        // Admin Analytics
        "admin.analytics.title": "Analytique",
        "admin.analytics.subtitle": "Plongée profonde dans la performance",
        "admin.analytics.loading": "Collecte d'informations...",
        "admin.analytics.total_revenue": "Revenu Total",
        "admin.analytics.conversion_rate": "Taux de Conversion",
        "admin.analytics.active_sessions": "Sessions Actives",
        "admin.analytics.avg_order_value": "Valeur Moyenne de Commande",
        "admin.analytics.revenue_over_time": "Revenu au Fil du Temps",
        "admin.analytics.top_products": "Top Produits",
        "admin.analytics.sales_count": "{count} ventes",
        "admin.analytics.no_sales_data": "Aucune donnée de vente pour le moment",
        "admin.analytics.channel_performance": "Performance des Canaux",
        "admin.analytics.visitor_locality": "Localité des visiteurs",
        "admin.analytics.visitor_locality_desc": "Implémentez le suivi de session pour voir les données géographiques en temps réel.",
        "admin.analytics.top_clients": "Meilleurs Clients",
        "admin.analytics.top_resellers": "Meilleurs Revendeurs",
        "admin.analytics.orders": "commandes",
        "admin.analytics.no_data": "Aucune donnée disponible",
        "admin.analytics.low_stock_alerts": "Alertes Stock Faible",
        "admin.analytics.in_stock": "en stock",
        "admin.analytics.no_low_stock": "Aucun article en stock faible",
        "admin.analytics.low_performing_products": "Produits à Faible Performance",
        "admin.analytics.sales": "ventes",
        "admin.analytics.no_low_sales": "Aucune donnée de vente faible",
        "admin.analytics.account_managers": "Gestionnaires de Compte",

        // Account Managers Page
        "account_managers.title": "Gestionnaires de Compte",
        "account_managers.subtitle": "Gérer les comptes d'entreprise et les affectations de revendeurs",
        "account_managers.add_manager": "Ajouter un Gestionnaire",
        "account_managers.create_title": "Créer un Gestionnaire de Compte",
        "account_managers.create_desc": "Remplissez les détails pour créer un nouveau compte de gestionnaire dédié.",
        "account_managers.full_name": "Nom Complet",
        "account_managers.work_email": "Email Professionnel",
        "account_managers.password": "Mot de Passe",
        "account_managers.phone": "Numéro de Téléphone",
        "account_managers.create_account": "Créer le Compte",
        "account_managers.created_success": "Gestionnaire de compte créé avec succès!",
        "account_managers.no_managers": "Aucun gestionnaire trouvé",
        "account_managers.no_managers_desc": "Commencez par ajouter votre premier gestionnaire pour gérer les relations avec les revendeurs.",
        "account_managers.assigned_accounts": "Comptes Assignés",
        "account_managers.prime_goal": "Objectif Prime",
        "account_managers.edit_goal": "Modifier l'Objectif",
        "account_managers.goal_updated": "Objectif Prime mis à jour avec succès",
        "account_managers.assign_resellers": "Assigner des Revendeurs",
        "account_managers.search_resellers": "Rechercher des revendeurs...",
        "account_managers.search_managers": "Rechercher des gestionnaires par nom ou email...",
        "account_managers.no_resellers_available": "Aucun revendeur disponible pour l'assignation",
        "account_managers.assignment_updated": "Affectation mise à jour!",
        "account_managers.reseller_unassigned": "Revendeur désassigné!",
        "account_managers.delete_confirm": "Êtes-vous sûr de vouloir supprimer {name}? Cela supprimera définitivement son compte et désassignera tous ses revendeurs.",
        "account_managers.deleted_success": "Gestionnaire de compte supprimé",
        "account_managers.unassign": "Désassigner",
        "account_managers.assign": "Assigner",
        "account_managers.delete_account": "Supprimer le Compte",
        "account_managers.manage_assignments": "Gérer les Affectations",
        "account_managers.select_resellers": "Sélectionnez les revendeurs dont ce gestionnaire sera responsable.",
        "account_managers.find_reseller": "Rechercher un revendeur par entreprise ou nom de contact...",
        "account_managers.no_match_search": "Aucun revendeur disponible ne correspond à votre recherche.",
        "account_managers.all_assigned": "Tous les revendeurs sont déjà assignés à d'autres gestionnaires de compte.",
        "account_managers.reassign": "Réassigner",
        "account_managers.set_prime_goal": "Définir l'Objectif Prime",
        "account_managers.set_goal_desc": "Définissez l'objectif de revenu pour",
        "account_managers.target_revenue": "Revenu Cible (MAD)",
        "account_managers.default_revenue": "La valeur par défaut est 200 000 MAD.",
        "account_managers.update": "Mettre à Jour",
        "account_managers.save": "Enregistrer",
        "account_managers.cancel": "Annuler",
        "account_managers.manager": "Gestionnaire",
        "account_managers.active": "Actif",
        "account_managers.company": "Entreprise",
        "account_managers.contact": "Contact",
        "account_managers.email": "Email",
        "account_managers.phone_label": "Téléphone",
        "account_managers.city": "Ville",
        "account_managers.loading": "Chargement des gestionnaires de compte...",
        "account_managers.error_loading": "Échec du chargement des gestionnaires de compte",

        // Admin Resellers Page
        "admin.resellers.title": "Performance des Revendeurs",
        "admin.resellers.subtitle": "Surveillance de {count} partenaires de distribution en gros actifs",
        "admin.resellers.total_resellers": "Total Revendeurs",
        "admin.resellers.total_partners": "Total Partenaires",
        "admin.resellers.total_wholesalers": "Total Grossistes",
        "admin.resellers.partner_network": "Réseau de Partenaires",
        "admin.resellers.total_spend": "Dépenses Totales",
        "admin.resellers.all_partners": "Tous les Partenaires",
        "admin.resellers.pending_approval": "En attente d'approbation",
        "admin.resellers.top_spend": "Meilleures Dépenses",
        "admin.resellers.search_placeholder": "Filtrer les partenaires par nom ou entreprise...",
        "admin.resellers.loading": "Initialisation des Données Partenaires...",
        "admin.resellers.reseller_identity": "Identité du Revendeur",
        "admin.resellers.company_ice": "Entreprise / ICE",
        "admin.resellers.performance": "Performance",
        "admin.resellers.location": "Localisation",
        "admin.resellers.account_manager": "Gestionnaire de Compte",
        "admin.resellers.nexus_profile": "Profil Nexus",
        "admin.resellers.personal_account": "Compte Personnel",
        "admin.resellers.ice": "ICE",
        "admin.resellers.na": "N/A",
        "admin.resellers.unknown": "Inconnu",
        "admin.resellers.unassigned": "Non Assigné",
        "admin.resellers.view_profile": "Voir le Profil",
        "admin.resellers.no_resellers": "Aucun Partenaire Détecté",
        "admin.resellers.no_resellers_description": "Essayez d'ajuster vos filtres pour trouver des entités de distribution correspondantes.",
        "admin.resellers.reseller": "Revendeur",
        "admin.resellers.partner": "Partenaire",
        "admin.resellers.wholesaler": "Grossiste",
        "admin.resellers.total_profit": "Bénéfice Total",
        "admin.resellers.error_loading": "Échec du chargement des revendeurs",

        // Admin Customers Page
        "admin.customers.title": "Ventes Invités",
        "admin.customers.subtitle": "Surveillance de {count} clients de détail directs",
        "admin.customers.guest_database": "Base de Données Invités",
        "admin.customers.total_guest_spend": "Dépenses Total Invités",
        "admin.customers.all_guests": "Tous les Invités",
        "admin.customers.top_spend": "Meilleures Dépenses",
        "admin.customers.search_placeholder": "Rechercher des invités par nom, email, téléphone ou ID de commande...",
        "admin.customers.loading": "Initialisation des Données Invités...",
        "admin.customers.guest_user": "Utilisateur Invité",
        "admin.customers.spend": "Dépenses",
        "admin.customers.orders": "Commandes",
        "admin.customers.last_order": "Dernière Commande",
        "admin.customers.na": "N/A",
        "admin.customers.unknown": "Inconnu",
        "admin.customers.no_guests": "Aucun invité trouvé",
        "admin.customers.customer_identity": "Identité du Client",
        "admin.customers.performance": "Performance",
        "admin.customers.location": "Localisation",
        "admin.customers.actions": "Actions",
        "admin.customers.total_spent": "Total Dépensé",
        "admin.customers.total_orders": "Total Commandes",
        "admin.customers.no_guests_found": "Aucun Invité Trouvé",
        "admin.customers.no_guests_description": "Il n'y a pas encore de clients invités correspondant à vos filtres.",

        // Reseller Dashboard
        "reseller.dashboard.title": "Tableau de Bord Revendeur",
        "reseller.dashboard.welcome_back": "Bon retour, {name}",
        "reseller.dashboard.browse_catalog": "Parcourir le Catalogue",
        "reseller.dashboard.total_orders": "Total Commandes",
        "reseller.dashboard.total_value": "Valeur Totale",
        "reseller.dashboard.organization_profile": "Profil de l'Organisation",
        "reseller.dashboard.company_name": "Nom de l'Entreprise",
        "reseller.dashboard.not_set": "Non défini",
        "reseller.dashboard.business_identification": "Identification Commerciale (ICE)",
        "reseller.dashboard.location": "Localisation",
        "reseller.dashboard.site": "Site",
        "reseller.dashboard.view": "Voir",
        "reseller.dashboard.dedicated_account_manager": "Gestionnaire de Compte Dédié",
        "reseller.dashboard.no_account_manager": "Aucun gestionnaire de compte assigné pour le moment",
        "reseller.dashboard.transaction_history": "Historique des Transactions",
        "reseller.dashboard.order": "Commande",
        "reseller.dashboard.orders": "Commandes",
        "reseller.dashboard.no_transactions": "Aucune Transaction Enregistrée",
        "reseller.dashboard.initialize_trade": "Initialiser le Commerce",
        "reseller.dashboard.initialize_desc": "Commencez votre parcours de gros aujourd'hui et débloquez les prix d'inventaire de niveau 1.",
        "reseller.dashboard.start_now": "Commencer Maintenant",
        "reseller.dashboard.reference_id": "ID de Référence",
        "reseller.dashboard.timestamp": "Horodatage",
        "reseller.dashboard.fulfillment": "Exécution",
        "reseller.dashboard.volume": "Volume",
        "reseller.dashboard.action": "Action",
        "reseller.dashboard.view_order": "Voir",
        "reseller.dashboard.total": "Total",
        "reseller.dashboard.signed_out": "Déconnexion réussie",

        // Manager Dashboard
        "manager.dashboard.title": "Tableau de Bord",
        "manager.dashboard.overview": "Aperçu de vos comptes assignés",
        "manager.dashboard.assigned_clients": "Clients Assignés",
        "manager.dashboard.clients_desc": "Revendeurs, Partenaires & Grossistes",
        "manager.dashboard.total_orders": "Total Commandes",
        "manager.dashboard.total_orders_desc": "Commandes de tous les temps",
        "manager.dashboard.total_revenue": "Revenu Total",
        "manager.dashboard.total_revenue_desc": "De toutes les commandes",
        "manager.dashboard.pending_orders": "Commandes en Attente",
        "manager.dashboard.pending_orders_desc": "Nécessitent une attention",
        "manager.dashboard.recent_orders": "Commandes Récentes",
        "manager.dashboard.recent_orders_desc": "Dernières commandes de vos clients",
        "manager.dashboard.view_all": "Voir Tout",
        "manager.dashboard.no_orders": "Aucune commande pour le moment",
        "manager.dashboard.assigned_clients_title": "Clients Assignés",
        "manager.dashboard.your_reseller_accounts": "Vos comptes revendeurs",
        "manager.dashboard.no_clients": "Aucun client assigné pour le moment",

        // Manager Orders
        "manager.orders.title": "Commandes",
        "manager.orders.subtitle": "Toutes les commandes de vos clients assignés",
        "manager.orders.search_placeholder": "Rechercher des commandes...",
        "manager.orders.filter_all": "Toutes",
        "manager.orders.filter_pending": "En Attente",
        "manager.orders.filter_processing": "En Traitement",
        "manager.orders.filter_shipped": "Expédiées",
        "manager.orders.filter_delivered": "Livrées",
        "manager.orders.filter_cancelled": "Annulées",
        "manager.orders.order_number": "N° Commande",
        "manager.orders.customer": "Client",
        "manager.orders.date": "Date",
        "manager.orders.status": "Statut",
        "manager.orders.total": "Total",
        "manager.orders.view": "Voir",
        "manager.orders.no_orders": "Aucune commande trouvée",
        "manager.orders.loading": "Chargement des commandes...",

        // Manager Order Details
        "manager.order_details.back": "Retour",
        "manager.order_details.order_number": "Commande n° {number}",
        "manager.order_details.bon_de_commande": "Bon de Commande",
        "manager.order_details.company_customer": "Entreprise / Client",
        "manager.order_details.contact": "Contact:",
        "manager.order_details.ref": "RÉF:",
        "manager.order_details.rid": "RID:",
        "manager.order_details.direct_order": "Commande Directe",
        "manager.order_details.current_status": "Statut Actuel",
        "manager.order_details.total": "Total",
        "manager.order_details.location": "Localisation",
        "manager.order_details.items_ordered": "Articles Commandés",
        "manager.order_details.items_count": "{count} Articles",
        "manager.order_details.img": "IMG",
        "manager.order_details.qty": "Qte:",
        "manager.order_details.each": "chacun",
        "manager.order_details.standard_option": "Option Standard",
        "manager.order_details.internal_notes": "Notes Internes",
        "manager.order_details.no_notes": "Aucune note interne pour le moment.",
        "manager.order_details.write_note": "Écrire une note...",
        "manager.order_details.system": "Système",
        "manager.order_details.timeline": "Historique",
        "manager.order_details.reason": "Raison:",
        "manager.order_details.by": "par",
        "manager.order_details.loading": "Chargement des détails de la commande...",
        "manager.order_details.not_found": "Commande introuvable.",
        "manager.order_details.status_updated": "Statut mis à jour : {status}",
        "manager.order_details.note_added": "Note interne ajoutée",

        // Bon de Commande (Print)
        "print.bon_de_commande": "BON DE COMMANDE",
        "print.order_number": "N° Commande:",
        "print.date": "Date:",
        "print.client": "CLIENT",
        "print.shipping_address": "ADRESSE DE LIVRAISON",
        "print.attn": "Attn:",
        "print.product": "PRODUIT",
        "print.quantity": "QUANTITÉ",
        "print.unit_price": "PRIX UNITAIRE",
        "print.total": "TOTAL",
        "print.subtotal": "Sous-total",
        "print.shipping": "Livraison",
        "print.footer_generated": "Ce document est généré automatiquement.",
        "print.signature": "CACHET ET SIGNATURE",

        // Assignment Modal
        "manager.assignment.title": "Assigner un Logisticien",
        "manager.assignment.subtitle": "L'expédition de la commande #{number}",
        "manager.assignment.search_placeholder": "Rechercher par nom ou ville...",
        "manager.assignment.recommended": "RECOMMANDÉ",

        // Manager Resellers
        "manager.resellers.title": "Clients",
        "manager.resellers.subtitle": "Vos revendeurs, partenaires et grossistes assignés",
        "manager.resellers.search_placeholder": "Rechercher des clients...",
        "manager.resellers.revenue_goal": "Objectif de chiffre d’affaires",
        "manager.resellers.current_revenue": "Chiffre d’affaires actuel",
        "manager.resellers.target": "Cible",
        "manager.resellers.progress": "Progression",
        "manager.resellers.company": "Entreprise",
        "manager.resellers.contact": "Contact",
        "manager.resellers.email": "Email",
        "manager.resellers.phone": "Téléphone",
        "manager.resellers.city": "Ville",
        "manager.resellers.total_orders": "Total Commandes",
        "manager.resellers.total_revenue": "Revenu Total",
        "manager.resellers.view_profile": "Voir le Profil",
        "manager.resellers.no_resellers": "Aucun client trouvé",
        "manager.resellers.loading": "Chargement des clients...",
        "account_managers.assigned_partners": "Partenaires Assignés",
        "common.unknown": "Inconnu",
    }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    // Force language to 'fr'
    const language: Language = "fr"

    const t = (key: string) => {
        const dict = translations["fr"] as Record<string, string>
        const value = dict[key]

        if (value) return value

        // Humanized fallback instead of showing raw i18n key
        const lastSegment = key.split('.').pop() || key
        const humanized = lastSegment.replace(/_/g, ' ')
        return humanized.charAt(0).toUpperCase() + humanized.slice(1)
    }

    const setLanguage = (lang: Language) => {
        // No-op, always stay on fr
        console.log("Language change requested to:", lang, "but application is locked to French.")
    }

    const toggleLanguage = () => {
        // No-op
    }

    useEffect(() => {
        document.documentElement.dir = "ltr"
        document.documentElement.lang = "fr"
    }, [])

    return (
        <LanguageContext.Provider value={{
            language,
            setLanguage,
            t,
            dir: "ltr",
            toggleLanguage
        }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider")
    }
    return context
}
