"use client"
// Build sync trigger v2

import React, { createContext, useContext, useEffect, useState } from "react"

type Language = "en" | "fr" | "ar"
type Direction = "ltr" | "rtl"

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
    dir: Direction
    toggleLanguage: () => void
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
    fr: {
        "common.currency": "MAD",
        // Navigation
        "nav.shop": "Boutique",
        "nav.collections": "Collections",
        "nav.about": "À propos",
        "nav.faq": "FAQ",
        "nav.search": "Rechercher",
        "nav.shop_now": "Acheter",
        "nav.view_all_collections": "Voir toutes les collections",

        // Login
        "login.welcome": "Miravet – Grossisterie vétérinaire de confiance",
        "login.join_network": "Intégrez notre réseau de partenaires et bénéficiez de solutions vétérinaires de qualité, d’offres exclusives et d’un accompagnement dédié pour développer votre activité.",
        "login.rights": "Tous droits réservés.",
        "login.sign_in": "Se connecter",
        "login.enter_credentials": "Entrez vos identifiants pour accéder à votre compte",
        "login.email": "E-mail",
        "login.password": "Mot de passe",
        "login.forgot_password": "Mot de passe oublié ?",
        "login.placeholder_email": "nom@exemple.com",
        "login.loading": "Chargement...",
        "login.or": "Ou",
        "login.register_reseller": "S'inscrire en tant que revendeur",
        "login.success": "Connexion réussie",
        "login.failed": "Échec de la connexion",

        // Reseller Registration
        "reseller.register.partner_program": "Réseau Partenaire Miravet",
        "reseller.register.become_partner": "Rejoignez un leader de la distribution vétérinaire",
        "reseller.register.partner_desc": "Bénéficiez d’offres exclusives, de solutions professionnelles et d’un support personnalisé pour développer votre activité.",
        "reseller.register.feature.pricing": "Offres exclusives revendeurs",
        "reseller.register.feature.manager": "Accompagnement commercial dédié",
        "reseller.register.feature.shipping": "Logistique performante et livraison rapide",
        "reseller.register.feature.warranty": "Qualité garantie et produits certifiés",
        "reseller.register.rights": "© 2026 Réseau Partenaire Miravet.",
        "reseller.register.title": "S'inscrire en tant que revendeur",
        "reseller.register.subtitle": "Veuillez remplir le formulaire ci-dessous avec les coordonnées de votre entreprise",
        "reseller.register.company_info": "Informations sur l'entreprise",
        "reseller.register.company_name": "Nom de l'entreprise",
        "reseller.register.ice": "Numéro ICE",
        "reseller.register.website": "Site web (optionnel)",
        "reseller.register.city": "Ville",
        "reseller.register.contact_person": "Personne de contact",
        "reseller.register.full_name": "Nom complet",
        "reseller.register.phone": "Numéro de téléphone",
        "reseller.register.work_email": "E-mail professionnel",
        "reseller.register.password": "Mot de passe",
        "reseller.register.submitting": "Envoi de la candidature...",
        "reseller.register.create_account": "Créer un compte revendeur",
        "reseller.register.already_have_account": "Vous avez déjà un compte ? Connectez-vous",
        "reseller.register.success_toast": "Votre compte revendeur a été créé et est en attente d'activation. Nous activerons votre compte bientôt.",
        "reseller.register.error_toast": "Erreur lors de l'envoi de la candidature",

        // Header Popups
        "header.categories": "Catégories",
        "header.browse_by_category": "Parcourir par catégorie",
        "header.face_care": "Ordinateurs & Portables",
        "header.face_care_desc": "Stations de travail haute performance",
        "header.hair_care": "Serveurs & Stockage",
        "header.hair_care_desc": "Solutions pour entreprises",
        "header.body_care": "Imprimantes & Scanners",
        "header.body_care_desc": "Impression professionnelle",
        "header.gift_sets": "Composants",
        "header.gift_sets_desc": "Processeurs, RAM & plus",
        "header.new_arrival": "Nouveautés",
        "header.argan_elixir": "Gaming",
        "header.argan_elixir_desc": "Performance ultime pour gamers",
        "header.signature": "Entreprise",
        "header.essentials": "Bureau",
        "header.premium": "Gaming",

        "hero.title_prefix": "Miravet",
        "hero.title_suffix": "Vétérinaire",
        "hero.subtitle": "Partenaire de confiance pour la vente de produits vétérinaires pour toutes les espèces d’animaux. Engagés à soutenir votre pratique avec des prix compétitifs, livraison rapide, service client de qualité.",
        "hero.shop_collection": "Parcourir les produits",
        "hero.explore_best_sellers": "Voir les meilleures ventes",
        "hero.fast_delivery": "Livraison Rapide",
        "hero.secure_checkout": "Paiement Sécurisé",
        "hero.easy_returns": "Garantie Officielle",
        "hero.pure_argan_oil": "Produits Authentiques",
        "hero.cold_pressed": "Meilleurs Prix",

        // Sections
        "section.featured_collections": "Départements Vedettes",
        "section.featured_desc": "Découvrez notre large gamme d'équipements informatiques",
        "section.best_sellers": "Nos Marques Partenaires",
        "section.best_sellers_desc": "Découvrez nos marques de confiance",
        "section.brands_store": "Notre Boutique des Marques",
        "section.brands_store_subtitle": "Distributeur officiel des leaders mondiaux de la santé animale",
        "section.all_categories": "Tout",
        "section.view_all_products": "Voir tous les produits",
        "section.load_more": "Charger plus",
        "section.why_choose": "Pourquoi choisir Miravet ?",
        "section.organic": "100% Authentique",
        "section.organic_desc": "Produits authentiques des grandes marques",
        "section.award_winning": "Leader du marché",
        "section.award_winning_desc": "Plus de 20 ans d'expérience",
        "section.cruelty_free": "Garantie Complète",
        "section.cruelty_free_desc": "Garantie constructeur officielle",
        "section.handcrafted": "Support Expert",
        "section.handcrafted_desc": "Conseils techniques par des pros",
        "section.limited_offer": "Offre Limitée",
        "section.promo_title": "25% de remise sur votre 1ère commande",
        "section.promo_desc": "Profitez de la meilleure offre pour votre première commande. Utilisez le code WELCOME25.",
        "section.get_offer": "Profiter de l'offre",
        "section.hurry_up": "Dépêchez-vous !",
        "section.view_collection": "Voir la collection",
        "section.exclusive_promos": "Offres & Promotions",
        "section.exclusive_promos_subtitle": "Découvrez nos meilleures offres exclusives pour les professionnels",

        // Newsletter
        "newsletter.title": "Restez informé",
        "newsletter.desc": "Abonnez-vous pour des offres exclusives et les nouveaux lancements de produits.",
        "newsletter.placeholder": "Entrez votre email",
        "newsletter.subscribe": "S'abonner",
        "newsletter.disclaimer": "En vous abonnant, vous acceptez notre politique de confidentialité. Désinscription à tout moment.",

        // WhatsApp
        "whatsapp.title": "Restez connecté sur WhatsApp",
        "whatsapp.desc": "Rejoignez notre liste VIP pour des remises exclusives et un accès prioritaire aux nouveautés.",
        "whatsapp.placeholder": "Numéro de téléphone",
        "whatsapp.button": "Rejoindre maintenant",
        "whatsapp.success_title": "Vous êtes sur la liste !",
        "whatsapp.success_desc": "Merci de votre inscription. Un cadeau de bienvenue vous a été envoyé.",
        "whatsapp.disclaimer": "En rejoignant, vous acceptez de recevoir des messages marketing sur WhatsApp.",
        "hero.schedule_call": "Prendre rendez-vous",
        "whatsapp.register_another": "Inscrire un autre numéro",
        "whatsapp.verified_updates": "Mises à jour vérifiées",
        "whatsapp.processing": "Traitement...",

        // Footer
        "footer.company": "Entreprise",
        "footer.support": "Support",
        "footer.legal": "Légal",
        "footer.our_story": "Notre histoire",
        "footer.sustainability": "Durabilité",
        "footer.press": "Presse",
        "footer.careers": "Carrières",
        "footer.contact_us": "Contactez-nous",
        "footer.shipping_info": "Livraison",
        "footer.track_order": "Suivre ma commande",
        "footer.privacy_policy": "Politique de confidentialité",
        "footer.terms": "Conditions d'utilisation",
        "footer.refund_policy": "Politique de remboursement",
        "footer.cookies": "Cookies",
        "footer.rights": "Tous droits réservés.",
        "footer.about_desc": "À propos de notre entreprise de grossisterie vétérinaire. Partenaire de confiance pour la vente de produits vétérinaires pour toutes les espèces d’animaux au Maroc.",
        "footer.privacy_short": "Confidentialité",
        "footer.terms_short": "Conditions",
        "footer.system_status": "Système Opérationnel",
        "section.services": "Services",
        "home.card1.title": "Centre de Santé",
        "home.card1.desc": "Soins médicaux premium",
        "home.card2.title": "Toilettage & Soins",
        "home.card2.desc": "Une touche de luxe",
        "home.card3.title": "Nutrition Premium",
        "home.card3.desc": "Alimentation saine et bio",
        "home.card4.title": "Chirurgie",
        "home.card4.desc": "Instruments dentaires & pros",
        "home.card5.title": "Laboratoire",
        "home.card5.desc": "Analyses & diagnostic",
        "home.card6.title": "Imagerie",
        "home.card6.desc": "Échographie & Radiologie",
        "home.card7.title": "Hygiène",
        "home.card7.desc": "Désinfection & sécurité",
        "home.card8.title": "Mobilier",
        "home.card8.desc": "Équipement clinique",
        "home.card9.title": "Pharmacie",
        "home.card9.desc": "Médicaments & Traitements",

        // Product & Cart
        "product.add_to_cart": "Ajouter au panier",
        "product.reviews": "avis",
        "product.in_stock": "En Stock",
        "product.low_stock": "Stock Faible",
        "product.out_of_stock": "Rupture de stock",
        "product.select_size": "Choisir la taille",
        "product.quantity": "Quantité",
        "product.features": "Caractéristiques Clés",
        "product.specifications": "Spécifications Techniques",
        "product.warranty": "Garantie & Support",
        "product.you_may_also_like": "Vous aimerez aussi",
        "cart.your_cart_empty": "Votre panier est vide",
        "cart.empty_desc": "Il semblerait que vous n'ayez rien ajouté à votre panier pour le moment.",
        "cart.start_shopping": "Commencer vos achats",
        "cart.shopping_cart": "Panier",
        "cart.items": "articles",
        "cart.order_summary": "Résumé de la commande",
        "cart.subtotal": "Sous-total",
        "cart.shipping": "Livraison",
        "cart.free": "Gratuit",
        "cart.total": "Total",
        "cart.proceed_checkout": "Passer à la caisse",
        "cart.promo_code": "Code Promo",
        "cart.apply": "Appliquer",
        "cart.applied": "Appliqué",
        "cart.enter_code": "Entrer le code",
        "cart.discount_applied": "Remise appliquée !",
        "cart.add_more_shipping": "Ajoutez plus pour la livraison gratuite",
        "cart.continue_shopping": "Continuer vos achats",
        "cart.trust.shipping": "Livraison Rapide",
        "cart.trust.secure": "Paiement Sécurisé",
        "cart.trust.returns": "Retours sous 30 jours",

        // Order statuses (for labels/badges)
        "order.status.pending": "En attente",
        "order.status.processing": "En traitement",
        "order.status.shipped": "Expédiée",
        "order.status.delivered": "Livrée",
        "order.status.cancelled": "Annulée",

        // Generic Statuses (used in Manager pages)
        "status.pending": "En attente",
        "status.processing": "En traitement",
        "status.shipped": "Expédiée",
        "status.delivered": "Livrée",
        "status.cancelled": "Annulée",

        // FAQ
        "faq.title": "Questions Fréquentes",
        "faq.subtitle": "Tout ce que vous devez savoir sur nos produits",
        "faq.q1": "Quels types de produits proposez-vous ?",
        "faq.a1": "Nous sommes grossiste en matériel et produits vétérinaires, incluant vaccins, médicaments, instruments de chirurgie et solutions de diagnostic.",
        "faq.q2": "Vos produits sont-ils certifiés ?",
        "faq.a2": "Oui, tous nos produits proviennent de laboratoires agréés et respectent les normes vétérinaires en vigueur au Maroc.",
        "faq.q3": "Auxquels professionnels vendez-vous ?",
        "faq.a3": "Nous vendons exclusivement aux cliniques vétérinaires, cabinets, pharmacies et éleveurs professionnels agréés.",
        "faq.q4": "Livrez-vous dans tout le Maroc ?",
        "faq.a4": "Oui, nous disposons d'un réseau logistique couvrant l'ensemble du territoire national avec respect de la chaîne du froid.",
        "faq.q6": "Proposez-vous un accompagnement technique ?",
        "faq.a6": "Oui, nos experts vous accompagnent dans le choix de vos équipements et l'utilisation de nos solutions de santé animale.",

        // Checkout
        "checkout.title": "Paiement",
        "checkout.contact_info": "Informations de contact",
        "checkout.full_name": "Nom complet",
        "checkout.phone": "Numéro de téléphone",
        "checkout.email": "Email (Optionnel)",
        "checkout.city": "Ville",
        "checkout.address": "Adresse",
        "checkout.pay": "Payer",
        "checkout.processing": "Traitement...",
        "checkout.success_title": "Commande Confirmée !",
        "checkout.continue_shopping": "Continuer vos achats",
        "checkout.cancel_title": "Paiement Annulé",
        "checkout.cancel_desc": "Votre paiement a été annulé. Aucun débit n'a été effectué.",
        "checkout.return_cart": "Retour au panier",
        "checkout.retry": "Réessayer",
        "validation.required": "Ce champ est requis",
        "validation.phone": "Veuillez entrer un numéro valide (min 10 car.)",
        "validation.email": "Veuillez entrer un email valide",
        "checkout.payment_method": "Mode de paiement",
        "checkout.payment_cod": "Paiement à la livraison",
        "checkout.payment_cod_desc": "Payez en espèces à la réception de votre commande",
        "checkout.payment_virement": "Virement Bancaire",
        "checkout.payment_virement_desc": "Détails du virement bancaire direct",
        "checkout.payment_cheque": "Paiement par chèque",
        "checkout.save_info": "Enregistrer ces informations pour la prochaine fois",
        "error.404.title": "Oups ! Page introuvable",
        "error.404.description": "Il semble que vous ayez pris un mauvais tournant. La page que vous recherchez n'existe pas ou a été déplacée.",
        "error.404.back_home": "Retour à l'accueil",

        // Success Page
        "success.thank_you": "Merci",
        "success.order_confirmed": "Votre commande est confirmée",
        "checkout.success_desc": "Nous avons bien reçu votre commande. Nous vous appellerons bientôt pour confirmer.",
        "success.coupon_title": "Un cadeau pour vous",
        "success.coupon_desc": "Utilisez ce code pour 20% de réduction sur votre prochain achat",
        "success.order_summary": "Résumé de la commande",

        // Timer
        "timer.days": "Jours",
        "timer.hours": "Heures",
        "timer.minutes": "Min",
        "timer.seconds": "Sec",
        "timer.loading": "Chargement...",

        // Accessibility
        "accessibility.go_to_slide": "Aller à la diapositive",

        // Dashboard - Admin
        "dashboard.admin.title": "Tableau de Bord",
        "dashboard.admin.overview": "Aperçu détaillé",
        "dashboard.admin.search_placeholder": "Rechercher des commandes, clients, produits... (Ctrl+K)",
        "dashboard.admin.export": "Exporter",
        "dashboard.admin.import": "Importer",

        "admin.dashboard.recent_orders.title": "Commandes récentes",
        "admin.dashboard.recent_orders.view_all": "Voir tout",
        "admin.dashboard.recent_orders.loading": "Chargement...",
        "admin.dashboard.recent_orders.empty": "Aucune commande récente.",
        "admin.dashboard.recent_orders.col_order_id": "N° Commande",
        "admin.dashboard.recent_orders.col_customer": "Client",
        "admin.dashboard.recent_orders.col_email": "Email",
        "admin.dashboard.recent_orders.col_amount": "Montant",
        "admin.dashboard.recent_orders.col_status": "Statut",
        "admin.dashboard.recent_orders.col_action": "Action",

        // Admin Orders
        "admin.orders.title": "Commandes",
        "admin.orders.subtitle": "Gérer et suivre les commandes",
        "admin.orders.export": "Exporter",
        "admin.orders.create_order": "Créer une commande",
        "admin.orders.search_placeholder": "Rechercher des commandes...",
        "admin.orders.status.all": "Tout",
        "admin.orders.status.processing": "En traitement",
        "admin.orders.status.delivered": "Livrée",
        "admin.orders.status.pending": "En attente",
        "admin.orders.status.cancelled": "Annulée",
        "admin.orders.table.order": "Commande",
        "admin.orders.table.date": "Date",
        "admin.orders.table.customer": "Client",
        "admin.orders.table.items": "Articles",
        "admin.orders.table.total": "Total",
        "admin.orders.table.status": "Statut",
        "admin.orders.table.actions": "Actions",
        "admin.orders.loading": "Chargement des commandes...",
        "admin.orders.no_orders": "Aucune commande trouvée",
        "admin.orders.no_orders_match": "Aucune commande ne correspond à vos critères",
        "admin.orders.showing": "Affichage de {current} sur {total} commandes",
        "admin.orders.view_details": "Voir les détails",

        // Admin Products
        "admin.products.title": "Produits",
        "admin.products.subtitle": "Gérez votre inventaire",
        "admin.products.import_csv": "Importer CSV",
        "admin.products.manage_categories": "Gérer les catégories",
        "admin.products.add_product": "Ajouter un produit",
        "admin.products.category_name_en": "Nom de catégorie (Anglais)",
        "admin.products.category_name_ar": "Nom de catégorie (Arabe)",
        "admin.products.add": "Ajouter",
        "admin.products.search_categories": "Rechercher des catégories...",
        "admin.products.delete_category_confirm": "Supprimer cette catégorie ? Les produits l'utilisant devront être recatégorisés.",
        "admin.products.stats.total_products": "Total Produits",
        "admin.products.stats.total_inventory": "Inventaire Total",
        "admin.products.stats.low_stock": "Stock Faible",
        "admin.products.stats.out_of_stock": "Rupture de Stock",
        "admin.products.search_placeholder": "Rechercher des produits...",
        "admin.products.table.product": "Produit",
        "admin.products.table.category": "Catégorie",
        "admin.products.table.price": "Prix",
        "admin.products.table.stock": "Stock",
        "admin.products.table.status": "Statut",
        "admin.products.table.actions": "Actions",
        "admin.products.no_products": "Aucun produit trouvé correspondant à vos critères.",
        "admin.products.delete_product_confirm": "Êtes-vous sûr de vouloir supprimer ce produit ?",
        "admin.products.qty": "Qté",
        "admin.products.units": "unités",
        "admin.products.uploading": "Téléchargement...",

        // Admin Sidebar
        "admin.sidebar.dashboard": "Tableau de bord",
        "admin.sidebar.orders": "Commandes",
        "admin.sidebar.products": "Produits",
        "admin.sidebar.customers": "Clients digital",
        "admin.sidebar.resellers": "Revendeurs",
        "admin.sidebar.suppliers": "Fournisseurs",
        "admin.sidebar.account_managers": "Commercial",
        "admin.sidebar.delivery_men": "Logisticiens",
        "admin.sidebar.shipping": "Livraison",
        "admin.sidebar.analytics": "Analytique",
        "admin.sidebar.hero_carousel": "Promo",
        "admin.sidebar.whatsapp_leads": "Dirige WhatsApp",
        "admin.sidebar.contact_messages": "Messages de contact",
        "admin.sidebar.career_applications": "Candidatures",
        "admin.sidebar.invoices": "Factures",
        "admin.sidebar.settings": "Paramètres",
        "admin.sidebar.brands": "Marques",
        "admin.sidebar.logout": "Déconnexion",

        // Admin Hero
        "admin.hero.title": "Promo",
        "admin.hero.subtitle": "Personnalisez le curseur de votre page d'accueil. Les images de haute qualité (16:9 ou 4:3) fonctionnent le mieux. Liez les diapositives aux produits pour stimuler les ventes. Important : Assurez-vous d'activer les diapositives pour qu'elles apparaissent dans la boutique.",
        "admin.hero.add_slide": "Ajouter une Diapositive",
        "admin.hero.refresh": "Actualiser",
        "admin.hero.change_image": "Changer l'Image",
        "admin.hero.title_label": "Titre",
        "admin.hero.subtitle_label": "Sous-titre",
        "admin.hero.placeholder_title": "Titre de la Diapositive",
        "admin.hero.placeholder_subtitle": "Petit texte au-dessus du titre",
        "admin.hero.linked_product": "Produit Lié",
        "admin.hero.no_link": "Aucun Lien (Image uniquement)",
        "admin.hero.select_product": "Sélectionner un Produit",
        "admin.hero.active": "Actif",
        "admin.hero.inactive": "Inactif",
        "admin.hero.save": "Enregistrer",
        "admin.hero.saved": "Enregistré",
        "admin.hero.delete": "Supprimer",
        "admin.hero.max_size": "Images max 5 Mo",
        "admin.hero.recommended_size": "Recommandé : 1920x1080px ou 1200x1200px",
        "admin.hero.slides_configured": "{count} Diapositives configurées",
        "admin.hero.toast.upload_image": "Veuillez télécharger un fichier image",
        "admin.hero.toast.image_large": "La taille de l'image doit être inférieure à 5 Mo",
        "admin.hero.toast.uploading": "Téléchargement de l'image...",
        "admin.hero.toast.upload_success": "Image téléchargée avec succès",
        "admin.hero.toast.upload_fail": "Échec de la mise à jour de l'image",
        "admin.hero.toast.adding": "Ajout d'une nouvelle diapositive...",
        "admin.hero.toast.add_success": "Diapositive ajoutée ! Téléchargez une image maintenant.",
        "admin.hero.toast.add_fail": "Échec de l'ajout de la diapositive",
        "admin.hero.toast.delete_confirm": "Êtes-vous sûr de vouloir supprimer cette diapositive ?",
        "admin.hero.toast.deleting": "Suppression de la diapositive...",
        "admin.hero.toast.delete_success": "Diapositive supprimée",
        "admin.hero.toast.delete_fail": "Échec de la suppression de la diapositive",
        "admin.hero.toast.no_image_fail": "Impossible d'activer une diapositive sans image",
        "admin.hero.toast.activating": "Activation...",
        "admin.hero.toast.deactivating": "Désactivation...",
        "admin.hero.toast.status_success_on": "Diapositive activée",
        "admin.hero.toast.status_success_off": "Diapositive désactivée",
        "admin.hero.toast.status_fail": "Échec de la mise à jour du statut",
        "admin.hero.toast.save_success": "Enregistré avec succès",
        "admin.hero.toast.save_fail": "Échec de l'enregistrement",

        // Admin Contacts
        "admin.contacts.back": "Retour au tableau de bord",
        "admin.contacts.title": "Messages de contact",
        "admin.contacts.list_title": "Messages des clients, partenaires et distributeurs",
        "admin.contacts.subtitle": "Cliquez sur le bouton \"Afficher\" pour lire le contenu complet du message dans une boîte de dialogue.",
        "admin.contacts.table.name": "Nom",
        "admin.contacts.table.email": "E-mail",
        "admin.contacts.table.phone": "Téléphone",
        "admin.contacts.table.type": "Type",
        "admin.contacts.table.message": "Message",
        "admin.contacts.table.date": "Date",
        "admin.contacts.no_messages": "Aucun message pour le moment. Connectez le formulaire de contact à une base de données pour voir les messages ici.",
        "admin.contacts.view": "Afficher",
        "admin.contacts.details_title": "Détails du message",
        "admin.contacts.label.name": "Nom :",
        "admin.contacts.label.email": "E-mail :",
        "admin.contacts.label.phone": "Téléphone :",
        "admin.contacts.label.company": "Entreprise :",
        "admin.contacts.label.type": "Type :",

        // Admin Careers
        "admin.careers.back": "Retour au tableau de bord",
        "admin.careers.title": "Candidatures",
        "admin.careers.list_title": "Candidatures pour rejoindre l'équipe",
        "admin.careers.subtitle": "Cliquez sur le bouton \"Afficher\" sur chaque ligne pour lire le résumé complet de la candidature dans une boîte de dialogue.",
        "admin.careers.table.name": "Nom",
        "admin.careers.table.email": "E-mail",
        "admin.careers.table.phone": "Téléphone",
        "admin.careers.table.role": "Rôle",
        "admin.careers.table.cv": "Fichier CV",
        "admin.careers.table.summary": "Résumé",
        "admin.careers.table.date": "Date",
        "admin.careers.no_applications": "Aucune candidature pour le moment. Connectez le formulaire de carrière à une base de données pour voir les candidatures ici.",
        "admin.careers.open_cv": "Ouvrir le CV",
        "admin.careers.no_file": "Aucun fichier",
        "admin.careers.view": "Afficher",
        "admin.careers.details_title": "Détails de la candidature",
        "admin.careers.label.name": "Nom :",
        "admin.careers.label.email": "E-mail :",
        "admin.careers.label.phone": "Téléphone :",
        "admin.careers.label.role": "Rôle :",
        "admin.careers.label.cv": "Fichier CV :",

        // Admin Order details (extra labels)
        "admin.orders.update_status": "Mettre à jour le statut",
        "admin.orders.timeline_title": "Historique des statuts",
        "admin.orders.timeline_empty": "Aucun journal disponible.",
        "admin.orders.customer_title": "Client",
        "admin.orders.customer_company": "Entreprise",
        "admin.orders.customer_contact": "Contact",
        "admin.orders.customer_email": "E-mail",

        // Admin Settings
        "admin.settings.title": "Configuration de l'Administration",
        "admin.settings.subtitle": "Paramètres globaux pour Miravet",
        "admin.settings.reset": "Réinitialiser",
        "admin.settings.update": "Mettre à jour les systèmes",
        "admin.settings.toast.success": "Paramètres mis à jour avec succès",
        "admin.settings.toast.error": "Échec de la mise à jour des paramètres",
        "admin.settings.toast.push_sent": "Envoyé à {count} appareil(s)",
        "admin.settings.toast.push_no_sub": "Aucun abonnement actif trouvé pour ce magasin.",
        "admin.settings.toast.push_fail": "Échec du déclenchement de la notification de test",
        "admin.settings.tabs.general": "Général",
        "admin.settings.tabs.marketing": "Marketing",
        "admin.settings.tabs.payments": "Paiements",
        "admin.settings.tabs.alerts": "Alertes",
        "admin.settings.tabs.security": "Sécurité",
        "admin.settings.tabs.team": "Équipe",
        "admin.settings.general.action_required": "Action Requise",
        "admin.settings.general.caught_up": "Tout est à jour ! Pas d'alertes urgentes.",
        "admin.settings.general.reminders_title": "Rappels Internes",
        "admin.settings.general.reminders_desc": "Utilisez les notes internes sur les profils des revendeurs pour suivre les évaluations de performance et les besoins de suivi. Celles-ci sont partagées avec les administrateurs mais cachées aux revendeurs.",
        "admin.settings.general.identity_title": "Identité et Localisation",
        "admin.settings.general.label.store_name": "Nom du magasin",
        "admin.settings.general.label.support_email": "E-mail d'assistance",
        "admin.settings.general.label.currency": "Devise principale",
        "admin.settings.general.channels_title": "Canaux de contact",
        "admin.settings.general.label.whatsapp": "Numéro WhatsApp Business",
        "admin.settings.general.label.phone": "Ligne d'assistance directe",
        "admin.settings.marketing.title": "Annonces et Promotions Globales",
        "admin.settings.marketing.label.en_content": "Contenu Anglais",
        "admin.settings.marketing.label.ar_content": "Contenu Arabe",
        "admin.settings.marketing.label.announcement": "Annonce d'en-tête",
        "admin.settings.marketing.label.hero_title": "Titre de la section Hero",
        "admin.settings.marketing.label.hero_subtitle": "Sous-titre Hero",
        "admin.settings.marketing.label.promo_code": "Code Promo Actif",
        "admin.settings.marketing.promo_desc": "Appliqué lors du paiement et affiché dans certaines sections du magasin.",
        "admin.settings.payments.gateways_title": "Passerelles Standards",
        "admin.settings.payments.cod_title": "Paiement à la livraison (COD)",
        "admin.settings.payments.cod_desc": "Paiement standard au Maroc",
        "admin.settings.payments.cheque_title": "Paiement par chèque",
        "admin.settings.payments.cheque_desc": "Pour les entreprises et les sociétés",
        "admin.settings.payments.label.payee_info": "Informations sur le bénéficiaire",
        "admin.settings.payments.wire_title": "Virements Bancaires",
        "admin.settings.payments.transfer_title": "Virement",
        "admin.settings.payments.transfer_desc": "Paiement basé sur IBAN / RIB",
        "admin.settings.payments.label.banking_details": "Coordonnées bancaires",
        "admin.settings.alerts.title": "Notifications Push",
        "admin.settings.alerts.desc": "Alertes système en temps réel pour les commandes et le statut des stocks directement sur votre mobile ou votre bureau.",
        "admin.settings.alerts.global_toggle": "Service Push Global",
        "admin.settings.alerts.global_desc": "Interrupteur principal pour le moteur de notifications du magasin.",
        "admin.settings.alerts.register_device": "Enregistrer l'appareil actuel",
        "admin.settings.alerts.send_ping": "Envoyer un ping système",
        "admin.settings.alerts.guide_title": "Guide de configuration",
        "admin.settings.alerts.guide_ios_title": "iOS / iPhone",
        "admin.settings.alerts.guide_ios_desc": "1. Ouvrez cette page dans Safari\n2. Appuyez sur Partager → \"Sur l'écran d'accueil\"\n3. Ouvrez depuis l'écran d'accueil et abonnez-vous.",
        "admin.settings.alerts.guide_android_title": "Android / Bureau",
        "admin.settings.alerts.guide_android_desc": "Le navigateur doit être ouvert ou les tâches en arrière-plan activées. Fonctionne nativement sur Chrome/Edge.",
        "admin.settings.security.title": "Protection du Tableau de Bord",
        "admin.settings.security.desc": "Le code PIN administrateur protège les opérations sensibles et l'entrée dans le tableau de bord.",
        "admin.settings.security.label.pin": "Code PIN d'accès au système",
        "admin.settings.security.warning": "Attention : La modification du code PIN prendra effet immédiatement sur tous les points d'entrée administratifs.",
        "admin.settings.team.title": "Tableau de Bord Commercial",
        "admin.settings.team.label.fallback": "Message de statut par défaut",
        "admin.settings.team.fallback_desc": "Affiché dans le widget 'Action Requise' lorsqu'il n'y a pas de commandes en attente.",
        "admin.settings.team.label.guidance": "Conseils Internes",
        "admin.settings.team.guidance_desc": "Affiché dans le widget 'Rappels Internes' sur le tableau de bord commercial.",

        // Admin WhatsApp
        "admin.whatsapp.back": "Retour au tableau de bord",
        "admin.whatsapp.title": "Dirige WhatsApp",
        "admin.whatsapp.list_title": "Liste des abonnés WhatsApp",
        "admin.whatsapp.subtitle": "Cette page est un espace réservé pour afficher les numéros du formulaire.",
        "admin.whatsapp.table.country": "Code pays",
        "admin.whatsapp.table.phone": "Téléphone",
        "admin.whatsapp.table.date": "Abonné le",
        "admin.whatsapp.no_data": "Aucune donnée pour le moment.",

        // Admin Shipping
        "admin.shipping.title": "Règles de Livraison",
        "admin.shipping.subtitle": "Contrôlez les frais de livraison et les seuils de livraison gratuite pour différents types de clients.",
        "admin.shipping.refresh": "Actualiser",
        "admin.shipping.save_rules": "Enregistrer les Règles",
        "admin.shipping.customer_rules": "Règles Client {role}",
        "admin.shipping.reseller_rules": "Règles Revendeur",
        "admin.shipping.partner_rules": "Règles Partenaire",
        "admin.shipping.wholesaler_rules": "Règles Grossiste",
        "admin.shipping.configure_costs": "Configurer les coûts et seuils",
        "admin.shipping.status": "Statut",
        "admin.shipping.base_cost": "Frais de Livraison de Base",
        "admin.shipping.fixed_fee_desc": "Frais fixes ajoutés aux commandes inférieures au seuil.",
        "admin.shipping.free_threshold_amount": "Livraison Gratuite (Montant)",
        "admin.shipping.amount_required_desc": "Montant requis pour la livraison gratuite.",
        "admin.shipping.free_threshold_items": "Livraison Gratuite (Articles)",
        "admin.shipping.min_items_desc": "Nombre minimum d'articles requis pour la livraison gratuite.",
        "admin.shipping.order_logic": "Logique de commande :",
        "admin.shipping.rule_logic_desc": "Les commandes coûteront {price} {currency} sauf si elles dépassent {threshold} {currency} ou contiennent au moins {items} articles.",
        "admin.shipping.rule_disabled": "La règle de livraison est actuellement désactivée.",
        "admin.shipping.no_rules": "Aucune règle de livraison trouvée. Veuillez vérifier la configuration de la base de données.",
        "admin.shipping.retry": "Réessayer le chargement",
        "admin.shipping.success_update": "Paramètres de livraison mis à jour avec succès",
        "admin.shipping.error_update": "Échec de la mise à jour des paramètres",

        // Admin Analytics
        "admin.analytics.title": "Analytique",
        "admin.analytics.subtitle": "Plongée profonde dans la performance",
        "admin.analytics.loading": "Collecte d'informations...",
        "admin.analytics.total_revenue": "Revenu Total",
        "admin.analytics.conversion_rate": "Taux de Conversion",
        "admin.analytics.active_sessions": "Sessions Actives",
        "admin.analytics.avg_order_value": "Valeur Moyenne de Commande",
        "admin.analytics.revenue_over_time": "Revenu au Fil du Temps",
        "admin.analytics.top_products": "Top Produits",
        "admin.analytics.sales_count": "{count} ventes",
        "admin.analytics.no_sales_data": "Aucune donnée de vente pour le moment",
        "admin.analytics.channel_performance": "Performance des Canaux",
        "admin.analytics.visitor_locality": "Localité des visiteurs",
        "admin.analytics.visitor_locality_desc": "Implémentez le suivi de session pour voir les données géographiques en temps réel.",
        "admin.analytics.top_clients": "Meilleurs Clients",
        "admin.analytics.top_resellers": "Meilleurs Revendeurs",
        "admin.analytics.orders": "commandes",
        "admin.analytics.no_data": "Aucune donnée disponible",
        "admin.analytics.low_stock_alerts": "Alertes Stock Faible",
        "admin.analytics.in_stock": "en stock",
        "admin.analytics.no_low_stock": "Aucun article en stock faible",
        "admin.analytics.low_performing_products": "Produits à Faible Performance",
        "admin.analytics.sales": "ventes",
        "admin.analytics.no_low_sales": "Aucune donnée de vente faible",
        "admin.analytics.account_managers": "Commercial",

        // Account Managers Page
        "account_managers.title": "Commercial",
        "account_managers.subtitle": "Gérer les commerciaux et les affectations de revendeurs",
        "account_managers.add_manager": "Ajouter un Commercial",
        "account_managers.create_title": "Créer un Commercial",
        "account_managers.create_desc": "Remplissez les détails pour créer un nouveau compte commercial dédié.",
        "account_managers.full_name": "Nom Complet",
        "account_managers.work_email": "Email Professionnel",
        "account_managers.password": "Mot de Passe",
        "account_managers.phone": "Numéro de Téléphone",
        "account_managers.create_account": "Créer le Compte",
        "account_managers.created_success": "Commercial créé avec succès!",
        "account_managers.no_managers": "Aucun commercial trouvé",
        "account_managers.no_managers_desc": "Commencez par ajouter votre premier commercial pour gérer les relations avec les revendeurs.",
        "account_managers.assigned_accounts": "Comptes Assignés",
        "account_managers.prime_goal": "Objectif Prime",
        "account_managers.edit_goal": "Modifier l'Objectif",
        "account_managers.goal_updated": "Objectif Prime mis à jour avec succès",
        "account_managers.assign_resellers": "Assigner des Revendeurs",
        "account_managers.search_resellers": "Rechercher des revendeurs...",
        "account_managers.search_managers": "Rechercher des commerciaux par nom ou email...",
        "account_managers.no_resellers_available": "Aucun revendeur disponible pour l'assignation",
        "account_managers.assignment_updated": "Affectation mise à jour!",
        "account_managers.reseller_unassigned": "Revendeur désassigné!",
        "account_managers.delete_confirm": "Êtes-vous sûr de vouloir supprimer {name}? Cela supprimera définitivement son compte et désassignera tous ses revendeurs.",
        "account_managers.deleted_success": "Commercial supprimé",
        "account_managers.unassign": "Désassigner",
        "account_managers.assign": "Assigner",
        "account_managers.delete_account": "Supprimer le Compte",
        "account_managers.manage_assignments": "Gérer les Affectations",
        "account_managers.select_resellers": "Sélectionnez les revendeurs dont ce commercial sera responsable.",
        "account_managers.find_reseller": "Rechercher un revendeur par entreprise ou nom de contact...",
        "account_managers.no_match_search": "Aucun revendeur disponible ne correspond à votre recherche.",
        "account_managers.all_assigned": "Tous les revendeurs sont déjà assignés à d'autres commerciaux.",
        "account_managers.reassign": "Réassigner",
        "account_managers.set_prime_goal": "Définir l'Objectif Prime",
        "account_managers.set_goal_desc": "Définissez l'objectif de revenu pour",
        "account_managers.target_revenue": "Revenu Cible (MAD)",
        "account_managers.default_revenue": "La valeur par défaut est 200 000 MAD.",
        "account_managers.update": "Mettre à Jour",
        "account_managers.save": "Enregistrer",
        "account_managers.cancel": "Annuler",
        "account_managers.manager": "Gestionnaire",
        "account_managers.active": "Actif",
        "account_managers.company": "Entreprise",
        "account_managers.contact": "Contact",
        "account_managers.email": "Email",
        "account_managers.phone_label": "Téléphone",
        "account_managers.city": "Ville",
        "account_managers.loading": "Chargement des commerciaux...",
        "account_managers.error_loading": "Échec du chargement des commerciaux",

        // Admin Resellers Page
        "admin.resellers.title": "Performance des Revendeurs",
        "admin.resellers.subtitle": "Surveillance de {count} partenaires de distribution en gros actifs",
        "admin.resellers.total_resellers": "Total Revendeurs",
        "admin.resellers.total_partners": "Total Partenaires",
        "admin.resellers.total_wholesalers": "Total Grossistes",
        "admin.resellers.partner_network": "Réseau de Partenaires",
        "admin.resellers.total_spend": "Dépenses Totales",
        "admin.resellers.all_partners": "Tous les Partenaires",
        "admin.resellers.pending_approval": "En attente d'approbation",
        "admin.resellers.top_spend": "Meilleures Dépenses",
        "admin.resellers.search_placeholder": "Filtrer les partenaires par nom ou entreprise...",
        "admin.resellers.loading": "Initialisation des Données Partenaires...",
        "admin.resellers.reseller_identity": "Identité du Revendeur",
        "admin.resellers.company_ice": "Entreprise / ICE",
        "admin.resellers.performance": "Performance",
        "admin.resellers.location": "Localisation",
        "admin.resellers.account_manager": "Commercial",
        "admin.resellers.nexus_profile": "Profil Nexus",
        "admin.resellers.personal_account": "Compte Personnel",
        "admin.resellers.ice": "ICE",
        "admin.resellers.na": "N/A",
        "admin.resellers.unknown": "Inconnu",
        "admin.resellers.unassigned": "Non Assigné",
        "admin.resellers.view_profile": "Voir le Profil",
        "admin.resellers.no_resellers": "Aucun Partenaire Détecté",
        "admin.resellers.no_resellers_description": "Essayez d'ajuster vos filtres pour trouver des entités de distribution correspondantes.",
        "admin.resellers.reseller": "Revendeur",
        "admin.resellers.partner": "Partenaire",
        "admin.resellers.wholesaler": "Grossiste",
        "admin.resellers.total_profit": "Bénéfice Total",
        "admin.resellers.error_loading": "Échec du chargement des revendeurs",

        // Admin Customers Page
        "admin.customers.title": "Client Digital",
        "admin.customers.subtitle": "Surveillance de {count} clients digitaux directs",
        "admin.customers.guest_database": "Base de données Digital",
        "admin.customers.total_guest_spend": "Dépenses Total Digital",
        "admin.customers.all_guests": "Tous les Clients",
        "admin.customers.top_spend": "Meilleures Dépenses",
        "admin.customers.search_placeholder": "Rechercher des clients par nom, email, téléphone ou ID de commande...",
        "admin.customers.loading": "Initialisation des Données...",
        "admin.customers.guest_user": "Client Digital",
        "admin.customers.spend": "Dépenses",
        "admin.customers.orders": "Commandes",
        "admin.customers.last_order": "Dernière Commande",
        "admin.customers.na": "N/A",
        "admin.customers.unknown": "Inconnu",
        "admin.customers.no_guests": "Aucun client digital trouvé",
        "admin.customers.customer_identity": "Identité du Client",
        "admin.customers.performance": "Performance",
        "admin.customers.location": "Localisation",
        "admin.customers.actions": "Actions",
        "admin.customers.total_spent": "Total Dépensé",
        "admin.customers.total_orders": "Total Commandes",
        "admin.customers.no_guests_found": "Aucun Client Trouvé",
        "admin.customers.no_guests_description": "Il n'y a pas encore de clients digitaux correspondant à vos filtres.",

        // Reseller Dashboard
        "reseller.dashboard.title": "Tableau de Bord Revendeur",
        "reseller.dashboard.welcome_back": "Bon retour, {name}",
        "reseller.dashboard.browse_catalog": "Parcourir le Catalogue",
        "reseller.dashboard.total_orders": "Total Commandes",
        "reseller.dashboard.total_value": "Valeur Totale",
        "reseller.dashboard.organization_profile": "Profil de l'Organisation",
        "reseller.dashboard.company_name": "Nom de l'Entreprise",
        "reseller.dashboard.not_set": "Non défini",
        "reseller.dashboard.business_identification": "Identification Commerciale (ICE)",
        "reseller.dashboard.location": "Localisation",
        "reseller.dashboard.site": "Site",
        "reseller.dashboard.view": "Voir",
        "reseller.dashboard.dedicated_account_manager": "Commercial Dédié",
        "reseller.dashboard.no_account_manager": "Aucun commercial assigné pour le moment",
        "reseller.dashboard.transaction_history": "Historique des Transactions",
        "reseller.dashboard.order": "Commande",
        "reseller.dashboard.orders": "Commandes",
        "reseller.dashboard.no_transactions": "Aucune Transaction Enregistrée",
        "reseller.dashboard.initialize_trade": "Initialiser le Commerce",
        "reseller.dashboard.initialize_desc": "Commencez votre parcours de gros aujourd'hui et débloquez les prix d'inventaire de niveau 1.",
        "reseller.dashboard.start_now": "Commencer Maintenant",
        "reseller.dashboard.reference_id": "ID de Référence",
        "reseller.dashboard.timestamp": "Horodatage",
        "reseller.dashboard.fulfillment": "Exécution",
        "reseller.dashboard.volume": "Volume",
        "reseller.dashboard.action": "Action",
        "reseller.dashboard.view_order": "Voir",
        "reseller.dashboard.total": "Total",
        "reseller.dashboard.signed_out": "Déconnexion réussie",

        // Manager Dashboard
        "manager.dashboard.title": "Tableau de Bord",
        "manager.dashboard.overview": "Aperçu de vos comptes assignés",
        "manager.dashboard.assigned_clients": "Clients Assignés",
        "manager.dashboard.clients_desc": "Revendeurs, Partenaires & Grossistes",
        "manager.dashboard.total_orders": "Total Commandes",
        "manager.dashboard.total_orders_desc": "Commandes de tous les temps",
        "manager.dashboard.total_revenue": "Revenu Total",
        "manager.dashboard.total_revenue_desc": "De toutes les commandes",
        "manager.dashboard.pending_orders": "Commandes en Attente",
        "manager.dashboard.pending_orders_desc": "Nécessitent une attention",
        "manager.dashboard.recent_orders": "Commandes Récentes",
        "manager.dashboard.recent_orders_desc": "Dernières commandes de vos clients",
        "manager.dashboard.view_all": "Voir Tout",
        "manager.dashboard.no_orders": "Aucune commande pour le moment",
        "manager.dashboard.assigned_clients_title": "Clients Assignés",
        "manager.dashboard.your_reseller_accounts": "Vos comptes revendeurs",
        "manager.dashboard.no_clients": "Aucun client assigné pour le moment",

        // Manager Orders
        "manager.orders.title": "Commandes",
        "manager.orders.subtitle": "Toutes les commandes de vos clients assignés",
        "manager.orders.search_placeholder": "Rechercher des commandes...",
        "manager.orders.filter_all": "Toutes",
        "manager.orders.filter_pending": "En Attente",
        "manager.orders.filter_processing": "En Traitement",
        "manager.orders.filter_shipped": "Expédiées",
        "manager.orders.filter_delivered": "Livrées",
        "manager.orders.filter_cancelled": "Annulées",
        "manager.orders.order_number": "N° Commande",
        "manager.orders.customer": "Client",
        "manager.orders.date": "Date",
        "manager.orders.status": "Statut",
        "manager.orders.total": "Total",
        "manager.orders.view": "Voir",
        "manager.orders.no_orders": "Aucune commande trouvée",
        "manager.orders.loading": "Chargement des commandes...",

        // Manager Order Details
        "manager.order_details.back": "Retour",
        "manager.order_details.order_number": "Commande n° {number}",
        "manager.order_details.bon_de_commande": "Bon de Commande",
        "manager.order_details.bon_de_livraison": "Bon de Livraison",
        "manager.order_details.company_customer": "Entreprise / Client",
        "manager.order_details.contact": "Contact:",
        "manager.order_details.ref": "RÉF:",
        "manager.order_details.rid": "RID:",
        "manager.order_details.direct_order": "Commande Directe",
        "manager.order_details.current_status": "Statut Actuel",
        "manager.order_details.total": "Total",
        "manager.order_details.location": "Localisation",
        "manager.order_details.items_ordered": "Articles Commandés",
        "manager.order_details.items_count": "{count} Articles",
        "manager.order_details.img": "IMG",
        "manager.order_details.qty": "Qte:",
        "manager.order_details.each": "chacun",
        "manager.order_details.standard_option": "Option Standard",
        "manager.order_details.internal_notes": "Notes Internes",
        "manager.order_details.no_notes": "Aucune note interne pour le moment.",
        "manager.order_details.write_note": "Écrire une note...",
        "manager.order_details.system": "Système",
        "manager.order_details.timeline": "Historique",
        "manager.order_details.reason": "Raison:",
        "manager.order_details.by": "par",
        "manager.order_details.loading": "Chargement des détails de la commande...",
        "manager.order_details.not_found": "Commande introuvable.",
        "manager.order_details.status_updated": "Statut mis à jour : {status}",
        "manager.order_details.note_added": "Note interne ajoutée",

        // Bon de Commande (Print)
        "print.bon_de_commande": "BON DE COMMANDE",
        "print.bon_de_livraison": "BON DE LIVRAISON",
        "print.order_number": "N° Commande:",
        "print.date": "Date:",
        "print.client": "CLIENT",
        "print.shipping_address": "ADRESSE DE LIVRAISON",
        "print.attn": "Attn:",
        "print.product": "PRODUIT",
        "print.quantity": "QUANTITÉ",
        "print.unit_price": "PRIX UNITAIRE",
        "print.total": "TOTAL",
        "print.subtotal": "Sous-total",
        "print.shipping": "Livraison",
        "print.footer_generated": "Ce document est généré automatiquement.",
        "print.signature": "CACHET ET SIGNATURE",

        // Assignment Modal
        "manager.assignment.title": "Assigner un Logisticien",
        "manager.assignment.subtitle": "L'expédition de la commande #{number}",
        "manager.assignment.search_placeholder": "Rechercher par nom ou ville...",
        "manager.assignment.recommended": "RECOMMANDÉ",

        // Manager Resellers
        "manager.resellers.title": "Clients",
        "manager.resellers.subtitle": "Vos revendeurs, partenaires et grossistes assignés",
        "manager.resellers.search_placeholder": "Rechercher des clients...",
        "manager.resellers.revenue_goal": "Objectif de chiffre d’affaires",
        "manager.resellers.current_revenue": "Chiffre d’affaires actuel",
        "manager.resellers.target": "Cible",
        "manager.resellers.progress": "Progression",
        "manager.resellers.company": "Entreprise",
        "manager.resellers.contact": "Contact",
        "manager.resellers.email": "Email",
        "manager.resellers.phone": "Téléphone",
        "manager.resellers.city": "Ville",
        "manager.resellers.total_orders": "Total Commandes",
        "manager.resellers.total_revenue": "Revenu Total",
        "manager.resellers.view_profile": "Voir le Profil",
        "manager.resellers.no_resellers": "Aucun client trouvé",
        "manager.resellers.loading": "Chargement des clients...",
        "account_managers.assigned_partners": "Partenaires Assignés",
        "common.unknown": "Inconnu",
    },
    en: {
        "common.currency": "MAD",
        // Navigation
        "nav.shop": "Shop",
        "nav.collections": "Collections",
        "nav.about": "About",
        "nav.faq": "FAQ",
        "nav.search": "Search",
        "nav.shop_now": "Shop Now",
        "nav.view_all_collections": "View all collections",

        // Login
        "login.welcome": "Miravet – Trusted Veterinary Wholesaler",
        "login.join_network": "Join our partner network and benefit from quality veterinary solutions, exclusive offers, and dedicated support to grow your business.",
        "login.rights": "All rights reserved.",
        "login.sign_in": "Sign In",
        "login.enter_credentials": "Enter your credentials to access your account",
        "login.email": "Email",
        "login.password": "Password",
        "login.forgot_password": "Forgot password?",
        "login.placeholder_email": "name@example.com",
        "login.loading": "Loading...",
        "login.or": "Or",
        "login.register_reseller": "Register as a Reseller",
        "login.success": "Logged in successfully",
        "login.failed": "Login failed",

        // Reseller Registration
        "reseller.register.partner_program": "Miravet Partner Network",
        "reseller.register.become_partner": "Join a Leader in Veterinary Distribution",
        "reseller.register.partner_desc": "Benefit from exclusive offers, professional solutions, and personalized support to grow your business.",
        "reseller.register.feature.pricing": "Exclusive Reseller Offers",
        "reseller.register.feature.manager": "Dedicated Sales Support",
        "reseller.register.feature.shipping": "High-Performance Logistics & Fast Delivery",
        "reseller.register.feature.warranty": "Guaranteed Quality & Certified Products",
        "reseller.register.rights": "© 2026 Miravet Partner Network.",
        "reseller.register.title": "Register as a Reseller",
        "reseller.register.subtitle": "Please fill out the form below with your company details",
        "reseller.register.company_info": "Company Information",
        "reseller.register.company_name": "Company Name",
        "reseller.register.ice": "ICE Number",
        "reseller.register.website": "Website (Optional)",
        "reseller.register.city": "City",
        "reseller.register.contact_person": "Contact Person",
        "reseller.register.full_name": "Full Name",
        "reseller.register.phone": "Phone Number",
        "reseller.register.work_email": "Work Email",
        "reseller.register.password": "Password",
        "reseller.register.submitting": "Submitting Application...",
        "reseller.register.create_account": "Create Reseller Account",
        "reseller.register.already_have_account": "Already have an account? Log in",
        "reseller.register.success_toast": "Your reseller account has been created and is pending activation. We will activate your account soon.",
        "reseller.register.error_toast": "Error submitting application",

        // Header Popups
        "header.categories": "Categories",
        "header.browse_by_category": "Browse by category",
        "header.face_care": "Computers & Laptops",
        "header.face_care_desc": "High performance workstations",
        "header.hair_care": "Servers & Storage",
        "header.hair_care_desc": "Business solutions",
        "header.body_care": "Printers & Scanners",
        "header.body_care_desc": "Professional printing",
        "header.gift_sets": "Components",
        "header.gift_sets_desc": "Processors, RAM & more",
        "header.new_arrival": "New Arrivals",
        "header.argan_elixir": "Gaming",
        "header.argan_elixir_desc": "Ultimate performance for gamers",
        "header.signature": "Business",
        "header.essentials": "Office",
        "header.premium": "Gaming",

        "hero.title_prefix": "Miravet",
        "hero.title_suffix": "Veterinary",
        "hero.subtitle": "Trusted partner for wholesale veterinary products for all animal species. Committed to supporting your practice with competitive prices, fast delivery, and quality customer service.",
        "hero.shop_collection": "Browse Products",
        "hero.explore_best_sellers": "View Best Sellers",
        "hero.fast_delivery": "Fast Delivery",
        "hero.secure_checkout": "Secure Payment",
        "hero.easy_returns": "Official Warranty",
        "hero.pure_argan_oil": "Authentic Products",
        "hero.cold_pressed": "Best Prices",

        // Sections
        "section.featured_collections": "Featured Departments",
        "section.featured_desc": "Discover our wide range of IT equipment",
        "section.best_sellers": "Our Partner Brands",
        "section.best_sellers_desc": "Discover our trusted brands",
        "section.brands_store": "Our Brands Store",
        "section.brands_store_subtitle": "Official distributor of world leaders in animal health",
        "section.all_categories": "All",
        "section.view_all_products": "View all products",
        "section.load_more": "Load more",
        "section.why_choose": "Why chooses Miravet?",
        "section.organic": "100% Authentic",
        "section.organic_desc": "Authentic products from major brands",
        "section.award_winning": "Market Leader",
        "section.award_winning_desc": "Over 20 years of experience",
        "section.cruelty_free": "Full Warranty",
        "section.cruelty_free_desc": "Official manufacturer warranty",
        "section.handcrafted": "Expert Support",
        "section.handcrafted_desc": "Technical advice by pros",
        "section.limited_offer": "Limited Offer",
        "section.promo_title": "25% discount on your 1st order",
        "section.promo_desc": "Enjoy the best offer for your first order. Use code WELCOME25.",
        "section.get_offer": "Get the offer",
        "section.hurry_up": "Hurry up!",
        "section.view_collection": "View collection",
        "section.exclusive_promos": "Exclusive Promotions",
        "section.exclusive_promos_subtitle": "Explore our best exclusive offers for veterinary professionals",

        // Newsletter
        "newsletter.title": "Stay Informed",
        "newsletter.desc": "Subscribe for exclusive offers and new product launches.",
        "newsletter.placeholder": "Enter your email",
        "newsletter.subscribe": "Subscribe",
        "newsletter.disclaimer": "By subscribing, you agree to our privacy policy. Unsubscribe at any time.",

        // WhatsApp
        "whatsapp.title": "Stay Connected on WhatsApp",
        "whatsapp.desc": "Join our VIP list for exclusive discounts and priority access to new arrivals.",
        "whatsapp.placeholder": "Phone number",
        "whatsapp.button": "Join Now",
        "whatsapp.success_title": "You're on the list!",
        "whatsapp.success_desc": "Thank you for joining. A welcome gift has been sent to you.",
        "whatsapp.disclaimer": "By joining, you agree to receive marketing messages on WhatsApp.",
        "hero.schedule_call": "Schedule a call",
        "whatsapp.register_another": "Register another number",
        "whatsapp.verified_updates": "Processing...",
        "whatsapp.processing": "Processing...",

        // Footer
        "footer.company": "Company",
        "footer.support": "Support",
        "footer.legal": "Legal",
        "footer.our_story": "Our Story",
        "footer.sustainability": "Sustainability",
        "footer.press": "Press",
        "footer.careers": "Careers",
        "footer.contact_us": "Contact Us",
        "footer.shipping_info": "Shipping",
        "footer.track_order": "Track my order",
        "footer.privacy_policy": "Privacy Policy",
        "footer.terms": "Terms of Use",
        "footer.refund_policy": "Refund Policy",
        "footer.cookies": "Cookies",
        "footer.rights": "All rights reserved.",
        "footer.about_desc": "Miravet - Your trusted partner for wholesale veterinary products and solutions in Morocco.",
        "footer.privacy_short": "Privacy",
        "footer.terms_short": "Terms",
        "footer.system_status": "System Operational",
        "home.card1.title": "Health Center",
        "home.card1.desc": "Premium Medical Care",
        "home.card2.title": "Grooming Salon",
        "home.card2.desc": "A Touch of Luxury",
        "home.card3.title": "Premium Nutrition",
        "home.card3.desc": "Healthy Organic Food",
        "home.card4.title": "Surgery",
        "home.card4.desc": "Dental & Pro Instruments",
        "home.card5.title": "Laboratory",
        "home.card5.desc": "Analyses & Diagnosis",
        "home.card6.title": "Imaging",
        "home.card6.desc": "Ultrasound & Radiology",
        "home.card7.title": "Hygiene",
        "home.card7.desc": "Disinfection & Safety",
        "home.card8.title": "Furniture",
        "home.card8.desc": "Clinical Equipment",
        "home.card9.title": "Pharmacy",
        "home.card9.desc": "Medicines & Treatments",
        "section.services": "Services",

        // Product & Cart
        "product.add_to_cart": "Add to cart",
        "product.reviews": "reviews",
        "product.in_stock": "In Stock",
        "product.low_stock": "Low Stock",
        "product.out_of_stock": "Out of stock",
        "product.select_size": "Choose size",
        "product.quantity": "Quantity",
        "product.features": "Key Features",
        "product.specifications": "Technical Specifications",
        "product.warranty": "Warranty & Support",
        "product.you_may_also_like": "You may also like",
        "cart.your_cart_empty": "Your cart is empty",
        "cart.empty_desc": "It seems you haven't added anything to your cart yet.",
        "cart.start_shopping": "Start shopping",
        "cart.shopping_cart": "Panier",
        "cart.items": "items",
        "cart.order_summary": "Order summary",
        "cart.subtotal": "Subtotal",
        "cart.shipping": "Shipping",
        "cart.free": "Free",
        "cart.total": "Total",
        "cart.proceed_checkout": "Proceed to checkout",
        "cart.promo_code": "Promo Code",
        "cart.apply": "Apply",
        "cart.applied": "Applied",
        "cart.enter_code": "Enter code",
        "cart.discount_applied": "Discount applied!",
        "cart.add_more_shipping": "Add more for free shipping",
        "cart.continue_shopping": "Continue shopping",
        "cart.trust.shipping": "Fast Delivery",
        "cart.trust.secure": "Secure Payment",
        "cart.trust.returns": "30-day returns",

        // Order statuses
        "order.status.pending": "Pending",
        "order.status.processing": "Processing",
        "order.status.shipped": "Shipped",
        "order.status.delivered": "Delivered",
        "order.status.cancelled": "Cancelled",

        // Generic Statuses
        "status.pending": "Pending",
        "status.processing": "Processing",
        "status.shipped": "Shipped",
        "status.delivered": "Delivered",
        "status.cancelled": "Cancelled",

        // FAQ
        "faq.title": "Frequently Asked Questions",
        "faq.subtitle": "Everything you need to know about our products",
        "faq.q1": "What types of products do you sell?",
        "faq.a1": "We are a wholesale distributor of IT equipment, including PCs, servers, printers and networks.",
        "faq.q2": "Do you offer a warranty?",
        "faq.a2": "Yes, all our products are covered by the official manufacturer's warranty.",
        "faq.q3": "Do you sell to individuals?",
        "faq.a3": "We primarily serve businesses and resellers, but we also sell to individuals.",
        "faq.q4": "Where are you located?",
        "faq.a4": "We are based in Morocco and serve customers throughout the kingdom.",
        "faq.q5": "How to get a quote?",
        "faq.a5": "You can request a quote via our website or contact our sales team.",
        "faq.q6": "Do you provide technical support?",
        "faq.a6": "Yes, our expert team can assist you with technical questions and solution design.",

        // Checkout
        "checkout.title": "Checkout",
        "checkout.contact_info": "Contact Information",
        "checkout.full_name": "Full Name",
        "checkout.phone": "Phone Number",
        "checkout.email": "Email (Optional)",
        "checkout.city": "City",
        "checkout.address": "Address",
        "checkout.pay": "Pay",
        "checkout.processing": "Processing...",
        "checkout.success_title": "Order Confirmed!",
        "checkout.continue_shopping": "Continue shopping",
        "checkout.cancel_title": "Payment Cancelled",
        "checkout.cancel_desc": "Your payment was cancelled. No charges were made.",
        "checkout.return_cart": "Return to cart",
        "checkout.retry": "Retry",
        "validation.required": "This field is required",
        "validation.phone": "Please enter a valid number (min 10 characters)",
        "validation.email": "Please enter a valid email",
        "checkout.payment_method": "Payment Method",
        "checkout.payment_cod": "Cash on Delivery (COD)",
        "checkout.payment_cod_desc": "Pay in cash when you receive your order",
        "checkout.payment_virement": "Bank Transfer",
        "checkout.payment_virement_desc": "Direct bank transfer details",
        "checkout.payment_cheque": "Cheque Payment",
        "checkout.save_info": "Save this information for next time",
        "error.404.title": "Oops! Page Not Found",
        "error.404.description": "It looks like you've taken a wrong turn. The page you're looking for doesn't exist or has been moved.",
        "error.404.back_home": "Back to Home",

        // Success Page
        "success.thank_you": "Thank You",
        "success.order_confirmed": "Your order is confirmed",
        "checkout.success_desc": "We have received your order. We will call you soon to confirm.",
        "success.coupon_title": "A gift for you",
        "success.coupon_desc": "Use this code for 20% off your next purchase",
        "success.order_summary": "Order summary",

        // Timer
        "timer.days": "Days",
        "timer.hours": "Hours",
        "timer.minutes": "Min",
        "timer.seconds": "Sec",
        "timer.loading": "Loading...",

        // Accessibility
        "accessibility.go_to_slide": "Go to slide",
        "manager.order_details.bon_de_livraison": "Delivery Note",
        "print.bon_de_livraison": "DELIVERY NOTE",
        // Dashboard - Admin
        "dashboard.admin.title": "Dashboard",
        "dashboard.admin.overview": "Detailed overview",
        "dashboard.admin.search_placeholder": "Search orders, customers, products... (Ctrl+K)",
        "dashboard.admin.export": "Export",
        "dashboard.admin.import": "Import",

        "admin.dashboard.recent_orders.title": "Recent Orders",
        "admin.dashboard.recent_orders.view_all": "View all",
        "admin.dashboard.recent_orders.loading": "Loading...",
        "admin.dashboard.recent_orders.empty": "No recent orders.",
        "admin.dashboard.recent_orders.col_order_id": "Order No.",
        "admin.dashboard.recent_orders.col_customer": "Customer",
        "admin.dashboard.recent_orders.col_email": "Email",
        "admin.dashboard.recent_orders.col_amount": "Amount",
        "admin.dashboard.recent_orders.col_status": "Status",
        "admin.dashboard.recent_orders.col_action": "Action",

        // Admin Orders
        "admin.orders.title": "Orders",
        "admin.orders.subtitle": "Manage and track orders",
        "admin.orders.export": "Export",
        "admin.orders.create_order": "Create Order",
        "admin.orders.search_placeholder": "Search orders...",
        "admin.orders.status.all": "All",
        "admin.orders.status.processing": "Processing",
        "admin.orders.status.delivered": "Delivered",
        "admin.orders.status.pending": "Pending",
        "admin.orders.status.cancelled": "Cancelled",
        "admin.orders.table.order": "Order",
        "admin.orders.table.date": "Date",
        "admin.orders.table.customer": "Customer",
        "admin.orders.table.items": "Items",
        "admin.orders.table.total": "Total",
        "admin.orders.table.status": "Status",
        "admin.orders.table.actions": "Actions",
        "admin.orders.loading": "Loading orders...",
        "admin.orders.no_orders": "No orders found",
        "admin.orders.no_orders_match": "No orders match your criteria",
        "admin.orders.showing": "Showing {current} of {total} orders",
        "admin.orders.view_details": "View details",

        // Admin Products
        "admin.products.title": "Products",
        "admin.products.subtitle": "Manage your inventory",
        "admin.products.import_csv": "Import CSV",
        "admin.products.manage_categories": "Manage Categories",
        "admin.products.add_product": "Add Product",
        "admin.products.category_name_en": "Category Name (English)",
        "admin.products.category_name_ar": "Category Name (Arabic)",
        "admin.products.add": "Add",
        "admin.products.search_categories": "Search categories...",
        "admin.products.delete_category_confirm": "Delete this category? Products using it will need to be recategorized.",
        "admin.products.stats.total_products": "Total Products",
        "admin.products.stats.total_inventory": "Total Inventory",
        "admin.products.stats.low_stock": "Low Stock",
        "admin.products.stats.out_of_stock": "Out of Stock",
        "admin.products.search_placeholder": "Search products...",
        "admin.products.table.product": "Product",
        "admin.products.table.category": "Category",
        "admin.products.table.price": "Price",
        "admin.products.table.stock": "Stock",
        "admin.products.table.status": "Status",
        "admin.products.table.actions": "Actions",
        "admin.products.no_products": "No products found matching your criteria.",
        "admin.products.delete_product_confirm": "Are you sure you want to delete this product?",
        "admin.products.qty": "Qty",
        "admin.products.units": "units",
        "admin.products.uploading": "Uploading...",

        // Admin Sidebar
        "admin.sidebar.dashboard": "Dashboard",
        "admin.sidebar.orders": "Orders",
        "admin.sidebar.products": "Products",
        "admin.sidebar.customers": "Customers",
        "admin.sidebar.resellers": "Resellers",
        "admin.sidebar.suppliers": "Suppliers",
        "admin.sidebar.account_managers": "Account Managers",
        "admin.sidebar.delivery_men": "Logistics",
        "admin.sidebar.shipping": "Shipping",
        "admin.sidebar.analytics": "Analytics",
        "admin.sidebar.hero_carousel": "Promo",
        "admin.sidebar.whatsapp_leads": "Dirige WhatsApp",
        "admin.sidebar.contact_messages": "Contact Messages",
        "admin.sidebar.career_applications": "Applications",
        "admin.sidebar.invoices": "Invoices",
        "admin.sidebar.settings": "Settings",
        "admin.sidebar.brands": "Brands",
        "admin.sidebar.logout": "Logout",

        // Admin Hero
        "admin.hero.title": "Promo",
        "admin.hero.subtitle": "Customize your homepage slider.",
        "admin.hero.add_slide": "Add Slide",
        "admin.hero.refresh": "Refresh",
        "admin.hero.change_image": "Change Image",
        "admin.hero.title_label": "Title",
        "admin.hero.subtitle_label": "Subtitle",
        "admin.hero.save": "Save",
        "admin.hero.delete": "Delete",
        "admin.hero.toast.save_success": "Saved successfully",
        "admin.hero.toast.save_fail": "Failed to save",

        // Account Managers Page
        "account_managers.title": "Account Managers",
        "account_managers.subtitle": "Manage enterprise accounts",
        "account_managers.add_manager": "Add Manager",
        "account_managers.full_name": "Full Name",
        "account_managers.work_email": "Work Email",
        "account_managers.phone": "Phone Number",
        "account_managers.create_account": "Create Account",

        // Reseller Dashboard
        "reseller.dashboard.title": "Reseller Dashboard",
        "reseller.dashboard.welcome_back": "Welcome back, {name}",
        "reseller.dashboard.total_orders": "Total Orders",
        "reseller.dashboard.total_value": "Total Value",
        "reseller.dashboard.no_account_manager": "No account manager assigned yet",
        "reseller.dashboard.view_order": "View",

        // Manager Dashboard
        "manager.dashboard.title": "Dashboard",
        "manager.dashboard.assigned_clients": "Assigned Clients",
        "manager.dashboard.total_orders": "Total Orders",
        "manager.dashboard.total_revenue": "Total Revenue",
        "manager.dashboard.pending_orders": "Pending Orders",
        "manager.dashboard.view_all": "View All",

        "account_managers.assigned_partners": "Assigned Partners",
        "common.unknown": "Unknown",
    },
    ar: {
        "common.currency": "درهم",
        "nav.shop": "المتجر",
        "nav.collections": "المجموعات",
        "nav.about": "من نحن",
        "nav.faq": "الأسئلة الشائعة",
        "nav.search": "بحث",
        "nav.shop_now": "تسوق الآن",
        "nav.view_all_collections": "عرض جميع المجموعات",

        // Login
        "login.welcome": "ميرافت – تجارة الجملة البيطرية الموثوقة",
        "login.join_network": "انضم إلى شبكة شركائنا واستفد من حلول بيطرية عالية الجودة، وعروض حصرية، ودعم مخصص لتطوير نشاطك.",
        "login.rights": "جميع الحقوق محفوظة.",
        "login.sign_in": "تسجيل الدخول",
        "login.enter_credentials": "أدخل بياناتك للوصول إلى حسابك",
        "login.email": "البريد الإلكتروني",
        "login.password": "كلمة المرور",
        "login.forgot_password": "نسيت كلمة المرور؟",
        "login.placeholder_email": "name@example.com",
        "login.loading": "جاري التحميل...",
        "login.or": "أو",
        "login.register_reseller": "التسجيل كموزع معتمد",
        "login.success": "تم تسجيل الدخول بنجاح",
        "login.failed": "فشل تسجيل الدخول",

        // Reseller Registration
        "reseller.register.partner_program": "شبكة شركاء ميرافت",
        "reseller.register.become_partner": "انضم إلى شركة رائدة في التوزيع البيطري",
        "reseller.register.partner_desc": "استفد من عروض حصرية وحلول مهنية ودعم مخصص لتطوير نشاطك.",
        "reseller.register.feature.pricing": "عروض حصرية للموزعين",
        "reseller.register.feature.manager": "دعم تجاري مخصص",
        "reseller.register.feature.shipping": "لوجستيات فعالة وتوصيل سريع",
        "reseller.register.feature.warranty": "جودة مضمونة ومنتجات معتمدة",
        "reseller.register.rights": "© 2026 شبكة شركاء ميرافت.",
        "reseller.register.title": "تسجيل حساب موزع",
        "reseller.register.subtitle": "يرجى ملء النموذج أدناه بمعلومات شركتك",
        "reseller.register.company_info": "معلومات الشركة",
        "reseller.register.company_name": "اسم الشركة",
        "reseller.register.ice": "رقم التعريف الموحد (ICE)",
        "reseller.register.website": "الموقع الإلكتروني (اختياري)",
        "reseller.register.city": "المدينة",
        "reseller.register.contact_person": "معلومات الاتصال",
        "reseller.register.full_name": "الاسم الكامل",
        "reseller.register.phone": "رقم الهاتف",
        "reseller.register.work_email": "البريد الإلكتروني المهني",
        "reseller.register.password": "كلمة المرور",
        "reseller.register.submitting": "جاري إرسال الطلب...",
        "reseller.register.create_account": "إنشاء حساب موزع",
        "reseller.register.already_have_account": "لديك حساب بالفعل؟ تسجيل الدخول",
        "reseller.register.success_toast": "تم إنشاء حسابك بنجاح، وهو قيد المراجعة. سيتم تفعيل حسابك قريبًا.",
        "reseller.register.error_toast": "حدث خطأ أثناء التسجيل",

        // Header Popups
        "header.categories": "الفئات",
        "section.featured_collections": "الأقسام المميزة",
        "section.featured_desc": "اكتشف مجموعتنا الواسعة من المعدات البيطرية",
        "section.best_sellers": "علاماتنا التجارية الشريكة",
        "section.best_sellers_desc": "اكتشف علاماتنا التجارية الموثوقة",
        "section.brands_store": "متجر علاماتنا التجارية",
        "section.brands_store_subtitle": "الموزع الرسمي لقادة العالم في صحة الحيوان",
        "section.all_categories": "الكل",
        "hero.title_prefix": "ميرافت",
        "hero.title_suffix": "البيطري",
        "hero.subtitle": "شريكك الموثوق لبيع المنتجات البيطرية لجميع أنواع الحيوانات. ملتزمون بدعم ممارستكم بأسعار تنافسية، توصيل سريع، وخدمة عملاء عالية الجودة.",
        "hero.shop_collection": "تصفح المنتجات",
        "hero.fast_delivery": "توصيل سريع",
        "hero.secure_checkout": "دفع آمن",
        "hero.easy_returns": "ضمان رسمي",
        "product.add_to_cart": "إضافة إلى السلة",
        "product.in_stock": "في المخزن",
        "product.out_of_stock": "نفذت الكمية",
        "cart.shopping_cart": "سلة التسوق",
        "cart.order_summary": "ملخص الطلب",
        "cart.total": "المجموع",
        "cart.proceed_checkout": "إتمام الطلب",
        "checkout.title": "الدفع",
        "checkout.payment_method": "طريقة الدفع",
        "checkout.payment_cod": "الدفع عند الاستلام",
        "checkout.payment_cod_desc": "الدفع نقداً عند استلام الطلب",
        "checkout.payment_virement": "تحويل بنكي",
        "checkout.payment_virement_desc": "تفاصيل التحويل البنكي المباشر",
        "checkout.payment_cheque": "شيك بنكي",
        "checkout.save_info": "حفظ المعلومات للمرة القادمة",
        "error.404.title": "عذراً! الصفحة غير موجودة",
        "error.404.description": "يبدو أنك سلكت مساراً خاطئاً. الصفحة التي تبحث عنها غير موجودة أو تم نقلها.",
        "error.404.back_home": "العودة إلى الرئيسية",
        "success.thank_you": "شكراً لك",
        "success.order_confirmed": "تم تأكيد طلبك",

        // Admin Sidebar
        "admin.sidebar.dashboard": "لوحة التحكم",
        "admin.sidebar.orders": "الطلبات",
        "admin.sidebar.products": "المنتجات",
        "admin.sidebar.customers": "الزبائن",
        "admin.sidebar.resellers": "الموزعون",
        "admin.sidebar.suppliers": "الموردون",
        "admin.sidebar.account_managers": "المسؤولون التجاريون",
        "admin.sidebar.delivery_men": "عمال التوصيل",
        "admin.sidebar.shipping": "الشحن",
        "admin.sidebar.analytics": "التحليلات",
        "admin.sidebar.hero_carousel": "العروض",
        "admin.sidebar.whatsapp_leads": "طلبات واتساب",
        "admin.sidebar.contact_messages": "رسائل الاتصال",
        "admin.sidebar.career_applications": "طلبات التوظيف",
        "admin.sidebar.invoices": "الفواتير",
        "admin.sidebar.settings": "الإعدادات",
        "admin.sidebar.brands": "العلامات التجارية",
        "admin.sidebar.logout": "تسجيل الخروج",
        "home.card1.title": "مركز الصحة",
        "home.card1.desc": "رعاية طبية فاخرة",
        "home.card2.title": "صالون التجميل",
        "home.card2.desc": "لمسة من الرفاهية",
        "home.card3.title": "التغذية الممتازة",
        "home.card3.desc": "طعام صحي وعضوي",
        "home.card4.title": "الجراحة",
        "home.card4.desc": "أدوات طب الأسنان والمحترفين",
        "home.card5.title": "المختبر",
        "home.card5.desc": "التحاليل والتشخيص",
        "home.card6.title": "التصوير الطبي",
        "home.card6.desc": "الموجات فوق الصوتية والأشعة",
        "home.card7.title": "النظافة",
        "home.card7.desc": "التطهير والسلامة",
        "home.card8.title": "الأثاث الطبي",
        "home.card8.desc": "معدات العيادة",
        "home.card9.title": "الأدوية",
        "home.card9.desc": "علاجات وأدوية بيطرية",
        "section.services": "الخدمات",
        "hero.schedule_call": "تحديد موعد",
        "section.exclusive_promos": "العروض والحصريات",
        "section.exclusive_promos_subtitle": "اكتشف أفضل العروض الحصرية للمهنيين البياطرة",
        "manager.order_details.bon_de_livraison": "بون التسليم",
        "print.bon_de_livraison": "بون التسليم",
    }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>("fr")

    const t = (key: string) => {
        const dict = (translations as any)[language] || translations["fr"] as Record<string, string>
        const value = dict[key]

        if (value) return value

        // Humanized fallback instead of showing raw i18n key
        const lastSegment = key.split('.').pop() || key
        const humanized = lastSegment.replace(/_/g, ' ')
        return humanized.charAt(0).toUpperCase() + humanized.slice(1)
    }

    const setLanguage = (lang: Language) => {
        setLanguageState(lang)
    }

    const toggleLanguage = () => {
        if (language === 'en') setLanguage('fr')
        else if (language === 'fr') setLanguage('ar')
        else setLanguage('en')
    }

    useEffect(() => {
        const dir = language === "ar" ? "rtl" : "ltr"
        document.documentElement.dir = dir
        document.documentElement.lang = language
    }, [language])

    return (
        <LanguageContext.Provider value={{
            language,
            setLanguage,
            t,
            dir: language === "ar" ? "rtl" : "ltr",
            toggleLanguage
        }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider")
    }
    return context
}
